<div class="info">
    <div class="title">
        <h1><?php echo $this->info["title"] ?></h1>
        <h2><?php echo $this->info["description"] ?></h2>
    </div>
    <div class="intro">
        <ul>
            <?php $now = date('Y-m-d H:i:s');
            if($now < $this->info['count_time'] && $this->info['enable_promo']==1){?>
                <li class='product-info' attr-count-down="<?php echo $this->info['count_time']?>" attr-enable-promo="<?php echo $this->info['enable_promo']?>">
                </li>
                <?php if (count($this->list_variant) > 0 ) { ?>
                    <li class="price-variant">
                        <label>Giá tiền:</label>
                        <strong class="price-a">
                            <span id="selected_price_sales"><?php if($this->list_variant[0]['variant_price_flash_sale'] > 0) {echo number_format($this->list_variant[0]["variant_price_flash_sale"]). '&#8363';} else { echo number_format($this->list_variant[0]["variant_price_sales"]). '&#8363';}?></span>
                        </strong>
                        <strong  class="price-b <?php if ($this->list_variant[0]['variant_price'] == $this->list_variant[0]['variant_price_flash_sale']) {echo 'hidden';} ?> " id="selected_price"><?php echo ($this->list_variant[0]['variant_price']). '&#8363' ?></strong>
                    </li>
                <?php } else { ?>
                        <li class="product-info-price">
                            <label>Giá tiền:</label>
                            <strong class="price-a"><?php if ($this->info["price_flash_sale"] > 0) { echo number_format($this->info["price_flash_sale"]) . '&#8363';} else { echo number_format($this->info["price_sales"]) . '&#8363';} ?></strong>
                            <?php if ($this->info["price"] != $this->info["price_flash_sale"]) { ?>
                                <strong class="price-b"><?php echo number_format($this->info["price"]) . '&#8363' ?></strong>
                            <?php } ?>
                        </li>
                <?php } ?>
           <?php }else{?>
                <?php if (count($this->list_variant) > 0) { ?>
                <li class="price-variant">
                    <label>Giá tiền:</label>
                    <strong class="price-a">
                        <span id="selected_price_sales"><?php if($this->list_variant[0]['variant_price_sales'] > 0) {echo number_format($this->list_variant[0]['variant_price_sales']). '&#8363';} else { echo 'Liên hệ';}?></span>
                    </strong>
                    <strong  class="price-b <?php if ($this->list_variant[0]['variant_price'] == $this->list_variant[0]['variant_price_sales']) {echo 'hidden';} ?> " id="selected_price"><?php echo number_format($this->list_variant[0]['variant_price']). '&#8363' ?></strong>
                </li>
                <?php } else { ?>
                        <li class="product-info-price">
                            <label>Giá tiền:</label>
                            <strong class="price-a"><?php if ($this->info["price_sales"] > 0) { echo number_format($this->info["price_sales"]) . '&#8363';} else { echo 'Liên hệ';} ?></strong>
                            <?php if ($this->info["price"] != $this->info["price_sales"]) { ?>
                                <strong class="price-b"><?php echo number_format($this->info["price"]) . '&#8363' ?></strong>
                            <?php } ?>
                        </li>
                <?php } ?>
            <?php }?>
        
            <?php if (empty($this->info["product_note"]) == false) { ?>
                <li>
                    <label>Tình trạng:</label>
                    <strong class="status-b"><?php echo $this->info["product_note"]; ?></strong>
                </li>
            <?php } ?>
            <li>
                <label>Trạng thái:</label>
                <?php
                $isOutOfOrder = false;
                if( $this->info["status"] == STATUS_IN_OUT_STOCK ){
                    $isOutOfOrder = true;
                }elseif($this->info["status"] == -1){
                    $isOutOfOrder = true;
                }
                ?>
                <strong class="status-a" <?php if($isOutOfOrder == true ){?> style="color:#000"  <?php }?>><?php echo Commons::getProductStatus($this->info["status"]); ?></strong>
            </li>
            <?php if (empty($this->info["guarantee"]) == false) { ?>
                <li>
                    <label>Bảo hành:</label>
                    <strong><?php echo $this->info["guarantee"]; ?></strong>
                </li>
            <?php } ?>
            <li>
                <label>Danh mục:</label>
                <a target="_blank" href="/danh-muc/<?php echo $this->info["category_url"] ?>"><strong><?php echo $this->info["category_name"] ?></strong></a>
            </li>
            <?php if (empty($this->info["tag"]) == false) { ?>
                <?php
                $tagsList = explode(",", $this->info["tag"]);
                ?>
                <li>
                    <label>Từ khóa:</label>
                    <?php foreach ($tagsList as $value) { ?>
                        <a class="tag"><?php echo $value ?></a>
                    <?php } ?>
                </li>
            <?php } ?>
            <!--<li>-->
            <!--    <label>Chia sẻ:</label>-->
            <!--    <div class="share">-->
            <!--        <div class="sharethis-inline-share-buttons"></div>-->
            <!--    </div>-->
            <!--</li>-->
        </ul>
    </div>

    <!--Phân Loại-->
    <?php if( empty($this->list_variant) == false && is_array($this->list_variant) ){ ?>
        <?php
            // Tạo một mảng chứa thông tin về variant, bao gồm tên và giá tiền
            $variants = array();
            foreach( $this->list_variant as $variant ){
                if($variant['status'] == 1) { // Kiểm tra nếu status = 1 thì mới hiển thị variant
                    $variants[$variant['id']] = array(
                        'variant_name' => $variant['variant_name'],
                        'variant_price' =>$variant['variant_price'],
                        'variant_price_sales'=>$variant['variant_price_sales'],
                        'variant_price_flash_sale' => $variant['variant_price_flash_sale'],
                    );
                }
            }
        ?>
        <?php if( (count($variants) > 1 ) || ( count($variants) == 1 && empty($this->list_variant[0]['id']) == false && $this->list_variant[0]['id'] != 1 )){ ?>
            <div class="intro variant-box options" data-value="Loại">
                <p class="variant-label">
                    <label>Chọn phiên bản mua:</label>
                    <span id="selected_variant" ><?php echo !empty($this->list_variant[0]['variant_name']) ? $this->list_variant[0]['variant_name']:''?></span>
                </p>
                <ul class="variant-list">
                    <?php foreach( $this->list_variant as $key => $variant ){?>
                        <input type="hidden" data-var0-id="<?php echo $this->list_variant[0]['id']?>">
                        <?php 
                            if($variant['status'] == 1) { 
                                $active = '';
                                if($key == 0 ){
                                    $active = 'active';
                                }
                        ?>
                            <?php
                                if($now < $this->info['count_time'] and $variants[$variant['id']]['variant_price_flash_sale']>0 and $this->info['enable_promo']==1) {?>
                                    <li class="variant-items" data-id = "<?php echo $variant['id']?>" data-price-sales = "<?php echo $variants[$variant['id']]['variant_price_flash_sale'] ?>" data-price = "<?php echo $variants[$variant['id']]['variant_price'] ?>">
                                        <a class="<?php echo $active ?>" data-id="<?php echo $variant['id']?>" title="<?php echo $variant['variant_name']?>" data-price-sales = "<?php echo $variants[$variant['id']]['variant_price_flash_sale'] ?>" data-price = "<?php echo $variants[$variant['id']]['variant_price'] ?>" ><?php echo $variant['variant_name']?></a>
                                    </li>
                            <?php }else {?>
                                    <li class="variant-items" data-id = "<?php echo $variant['id']?>" data-price-sales = "<?php echo $variants[$variant['id']]['variant_price_sales'] ?>" data-price = "<?php echo $variants[$variant['id']]['variant_price'] ?>">
                                        <a class="<?php echo $active ?>" data-id="<?php echo $variant['id']?>" title="<?php echo $variant['variant_name']?>" data-price-sales = "<?php echo $variants[$variant['id']]['variant_price_sales'] ?>" data-price = "<?php echo $variants[$variant['id']]['variant_price'] ?>" ><?php echo $variant['variant_name']?></a>
                                    </li>
                            <?php }?>
                        <?php } ?>
                    <?php }?>
                </ul>
            </div>
        <?php } ?>
    <?php } ?>
    <!-- end Phân Loại-->
    <?php if( $this->info["price_sales"] > 0 && $this->info["status"] == 1 ) { ?>
        <?php echo $this->render('/san-pham/_purchase.phtml') ?>
    <?php } ?>

    <?php if(empty($this->list_combo_product)==false  ){?>
        <div class="combo-product" data-vc-id ="<?php echo $this->list_variant[0]['id'] ?>" >
            <?php $counter = 0; ?>
            <?php foreach($this->list_combo_product as $combo_product ) {?>
                 <!-- Chỉ hiển thị 2 combo ban đầu -->
                    <ul>
                        <strong class="name" style="line-height: 1.5;font-size: 1.25rem;display: block;padding-top:10px;text-align: center;"><?php echo $combo_product['title']?><br/></strong>
                        <div class="combo">
                            <?php 
                                foreach ($this->list_combo_detail as $combo_id => $combo_detail) {?>
                                <ul>
                                <?php if($combo_product['combo_id'] == $combo_id) {?>
                                    <?php  $totalPrice = 0;
                                        foreach ($combo_detail as $product){?>
                                            <li>
                                                <?php
                                                    $productUrl = "/" . $product["url_product"];
                                                    $productImgUrl = "";
                                                    if (empty($product["image"]) == false) {
                                                        $productImgUrl = "/upload/images" . $product["image"];
                                                    }
                                                    $price = $product['price_sales'];
                                                    $totalPrice += $price; 
                                                    ?>
                                                <a href="<?php echo $productUrl ?>" title="<?php echo $product['title'] ?>">
                                                    <?php echo $this->partial('/shared/_lazy_image.phtml', array(
                                                        'ratio' => '1x1',
                                                        'css' => 'photo',
                                                        'url' => $productImgUrl,
                                                        )) ?>
                                                </a>
                                            </li>   
                                            <img class="bt-plus" src="//c3-ebgames.eb-cdn.com.au/1.154.0/images/svg/plus.svg" alt="+">
                                <?php }?>
                                <?php } ?>
                                </ul>
                            <?php }?>
                            <div class="combo-info">
                                <strong class="price-total">Tổng giá tiền: <?php echo number_format($totalPrice) . '&#8363'  ?><br/></strong>
                                <strong class="price-a">Giá Combo Sale: <?php echo number_format($combo_product['total_discount']) . '&#8363'  ?><br/></strong> 
                            </div>
                        </div>
                        <?php if ($combo_product['total_discount'] > 0 && $this->status != STATUS_IN_OUT_STOCK) { ?>
                            <a class="btn cart cart_btn_combo my_btn" href="<?php echo $this->cart?>"
                            qty="1"
                            cid="<?php echo $combo_product['combo_id']?>" 
                            >
                            <i class="fa fa-cart-plus"></i> ADD All
                            </a>
                            <?php }else{ ?>
                            <a class="btn btn-danger my_btn" href="tel:+84906221218">
                                Tạm hết hàng
                            </a>
                        <?php } ?>
                        <div class="more-detail" style="margin-left:20px">
                            <div class="bt-divider" track="product-fbt-accordion-auto" style="cursor: pointer;padding:8px">
                                <span class="more-expand" style="display: inline;" data-combo-id ="<?php echo $combo_product['combo_id'] ?>">Xem chi tiết &nbsp;&#x25BC;</span>
                                <span class="more-collapse" style="display: none;" data-combo-id ="<?php echo $combo_product['combo_id'] ?>">Ẩn chi tiết &nbsp;&#x25B2;</span>
                                <span class="icon icon-chervon-down" style="transition: transform 250ms ease-in-out 0s; transform: rotate(0deg);" data-combo-id ="<?php echo $combo_product['combo_id'] ?>"></span>
                            </div>
                            <?php foreach ($this->list_combo_detail as $combo_id => $combo_detail) { ?>
                                <?php if($combo_product['combo_id'] == $combo_id) {?>
                                    <ul class="info-detail" style="display:none;" data-combo-id ="<?php echo $combo_product['combo_id'] ?>">
                                        <?php foreach($combo_detail as $product){?>
                                        <li style="border-top:1px solid gray; margin-right:20px">
                                            <?php
                                            $productUrl = "/" . $product["url_product"];        
                                            ?>
                                            <div class="meta">
                                                <a href="<?php echo $productUrl ?>" style="color:black;text-decoration: none;" title="<?php echo $product['title'] ?>">
                                                    <span class="name" style="color:black;text-decoration: none;">Sản phẩm: <?php echo $product['title']?><br/></span>
                                                </a>
                                                <?php
                                                    if($product['price'] >= $product['price_sales'] && $product['price_sales'] != ''  ) { ?>
                                                        <span class="price-a">Giá:<?php echo number_format($product['price_sales']) . '&#8363'  ?><br/></span>
                                                    <?php } 
                                                    else {?>
                                                        <span class="price-a">Giá:<?php echo number_format($product['price']) . '&#8363'  ?><br/></span>
                                                   <?php  } ?>
                                            </div>
                                        </li>
                                        <?php }?>
                                    </ul>
                                    <?php }?>
                            <?php } ?>
                        </div>
                    </ul>
                
                <?php $counter++; ?>
           <?php }?>
           <div class="show-hide" style="text-align: center;margin-bottom: 10px;">
               <?php if (count($this->list_combo_product) > 2) { ?> <!-- Kiểm tra xem có nhiều hơn 2 combo hay không -->
                    <button id="show-combo" class="combo-button">Xem thêm Combo</button>
                    <button id="hide-combo" class="combo-button" style="display: none;">Thu gọn</button>
                <?php } ?>
           </div>
        </div>
    <?php }?>
    <div class="guide">
        <?php
        $productContact = Commons::getSettingByKey($this->setting, PRODUCT_CONTACT);
        if (empty($productContact["value"]) == false) {
            echo $productContact["value"];
        }
        ?>
    </div>
</div>
<script type="application/ld+json">
    <?php
         $json_ld_data = [
            "@context" => "http://schema.org",
            "@type" => "product",
            "sku" => $this->info['id'],
            "name" => $this->info["title"],
            "description" => $this->info["description"],
            "image" => empty($this->info['image']) == false ? "https://herogame.vn/".PHOTO_PATH . $this->info['image']: "",
            "url" => "https://herogame.vn/".$this->info["url_product"],
            "offers" => [
                "@context" => "http://schema.org",
                "@type" => "offer",
                 "url" => "https://herogame.vn/".$this->info["url_product"],
                "price" => $this->info["price_sales"] > 0? $this->info["price_sales"]: $this->info["price"],
                "priceCurrency" => "VND",
                "availability" => 'https://schema.org/InStock',//"https://schema.org/OutOfStock"
            ],
            "brand" => [
                "@context" => "http://schema.org",
                "@type" => "Corporation", //Corporation, Thing, Brand
                "name" => ""
            ]
        ];
        echo json_encode($json_ld_data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    ?>
</script>

<style>
    li.product-info {
        background: #ee4d2d;
        display: flex;
        justify-content: space-between;
        align-items: center;
        justify-items: center;
        padding: 10px 0px !important;
    }
    strong.count_down_container {
        font-size: 24px!important;
        display: inline-block;
        color: white!important;
        margin-right: 10px;
    }
    label.flash-sale {
        display: block;
        margin: 0 10px;
        padding: 0;
        color: white;
        font-size: 20px;
        width: 8rem!important;
        font-weight: 600;
    }
    #show-combo, #hide-combo {
    background: blue;
    border-radius: 3px;
    border: none;
    color: white;
    padding: 5px 10px;
    cursor: pointer;
    }
    .combo-button:hover {
        opacity: 0.8;
    }
    .hidden {
        opacity: 0;
    }
    .combo-info {
        padding: 5px 0;
        display: flex;
        justify-content: space-evenly;
        width: 100%;
        margin: auto;
        border: 1px solid;;
        text-align: center;
        background: #dc2535;
        color: white;
    }
    .combo-product .cart_btn_combo {
        border-radius: 1px;
        background:green;
        color:white;
    }
    .combo-product {
        /* background: #80808038; */
    }
    .combo-product .combo>ul{
        display: flex;
        justify-content: center;
        flex-wrap: nowrap;
    }
    .combo-product .combo>ul>li{
        align-items: center;
        flex-basis: 27%;
    }
    .combo-product .imgh {
        width: 100%;
    
        margin: 10px 0;
   
    }
    .combo-product .combo>ul>li>div{
        align-self: flex-start;
    }
    ul>.bt-plus:last-of-type {
        display: none !important;
    }
   
    img.bt-plus {
        width: 30px;
        margin: 5px;
    }

    @media screen and (max-width: 768px) {
        .combo-product {
        padding-top:60px
        }
    }
</style>

<!-- Messenger Plugin chat Code -->
<div id="fb-root"></div>

<!-- Your Plugin chat code -->
<div id="fb-customer-chat" class="fb-customerchat">
</div>

<script>
  var chatbox = document.getElementById('fb-customer-chat');
  chatbox.setAttribute("page_id", "100111066262770");
  chatbox.setAttribute("attribution", "biz_inbox");
</script>

<!-- Your SDK code -->
<script>
  window.fbAsyncInit = function() {
    FB.init({
      xfbml            : true,
      version          : 'v17.0'
    });
  };

  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/vi_VN/sdk/xfbml.customerchat.js';
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>