<?php
$list_variant =!empty($this->list_variant) ? $this->list_variant: '';

$first_color_active = !empty($this->color_list[0]['id']) ? $this->color_list[0]['id']: '';
$color_index = array();
if(empty($this->info['image_color']) == false){
    $color_index = explode(",", $this->info['image_color']);
}

$thumbs_color = array();
if (empty($this->info['gallery']) == false) {
    $thumbs_color = explode(",", $this->info['gallery']);
    // echo "<pre>";print_r($thumbs_color);exit;
}

$thumbs = array();
if (empty($this->list_variant_img) == false) {
    $thumbs = $this->list_variant_img;
}
?>
<div class="photos">
    <div class="hidden-xs-down">
        <div class="main image_detail">
            <?php
            $url = '';
            if (empty($this->info['image']) == false) {
                $url = PHOTO_PATH . $this->info['image'];
            }
            ?>
            <?php
            echo $this->partial('/shared/_lazy_image.phtml', array(
                'ratio' => '1x1',
                'css' => 'photo',
                'url' => $url,
                'attrs' => array(
                    array(
                        'name' => 'id',
                        'value' => 'productMainPhoto'
                    ),
                    array(
                        'name' => 'data-zoom-image',
                        'value' => $url
                    )
                )
            ))
            ?>
            <div>
                <span id="click-left" class="btn-prev" >prev</span>
            </div>
            <div>
                <span id="click-right" class="btn-next" >next</span>
            </div>
        </div>
        <div id="productThumbPhotos" class="thumbs" style="margin-top:20px">
            <?php if (!empty($list_variant)) { ?>
                <?php foreach ($list_variant as $variant) { ?>
                    <?php $variant_images = $thumbs[$variant['id']]; ?>
                    <?php if(!empty($variant_images)) { ?>
                        <div class="variant-wrapper variant-<?php echo $variant['id'] ?> thumbs">
                            <?php foreach ($variant_images as $key => $value) { ?>
                                <?php $thumbClass = ($variant['id'] == $list_variant[0]['id'] && $key == 0) ? 'active' : ''; ?>
                                <?php $thumUrl = PHOTO_PATH . $value; ?> 
                                <a data-variantid="<?php echo $variant['id'] ?>" class="<?php //echo $thumbClass ?> image_thumbs variant_<?php echo $variant['id'] ?>" 
                                    data-image="<?php echo $thumUrl ?>"
                                    data-zoom-image="<?php echo $thumUrl ?>"
                                    <?php if($variant['id'] != $list_variant[0]['id']){?> style="display: none;"<?php }?>
                                >
                                    <?php
                                    echo $this->partial('/shared/_lazy_image.phtml', array(
                                        'ratio' => '1x1',
                                        'css' => 'photo',
                                        'url' => $thumUrl
                                    ));
                                    ?>
                                </a>
                            <?php } ?>
                        </div>
                    <?php } else { ?>
                        <div class="variant-wrapper variant-<?php echo $variant['id'] ?> thumbs">
                            <?php $defaultImage = PHOTO_PATH . $this->info['image']; ?>
                            <a data-variantid="<?php echo $variant['id'] ?>" class="image_thumbs variant_<?php echo $variant['id'] ?>"
                                data-image="<?php echo $defaultImage ?>"
                                data-zoom-image="<?php echo $defaultImage ?>"
                                <?php if($variant['id'] != $list_variant[0]['id']){?> style="display: none;"<?php }?>
                            >
                                <?php
                                echo $this->partial('/shared/_lazy_image.phtml', array(
                                    'ratio' => '1x1',
                                    'css' => 'photo',
                                    'url' => $defaultImage
                                ));
                                ?>
                            </a>
                        </div>
                    <?php } ?>
                <?php } ?>
            <?php } else {?>
            <div class="no-variant thumbs">
                <?php if (empty($thumbs_color) == false) { ?>
                    <?php foreach ($thumbs_color as $key => $value) { ?>
                        <?php $thumbClass = ($key == 0) ? 'active' : ''; ?>
                        <?php $thumUrl = PHOTO_PATH . $value; ?>
                        <a class="<?php //echo $thumbClass ?> image_thumbs color_<?php echo (empty($color_index) == true ) ? 1: $color_index[$key]?>" 
                        data-image="<?php echo $thumUrl ?>"
                        data-zoom-image="<?php echo $thumUrl ?>"
                        <?php if(empty($color_index) == false && $color_index[$key] != $first_color_active){?> style="display: none;"<?php }?>
                        >
                            <?php
                            echo $this->partial('/shared/_lazy_image.phtml', array(
                                'ratio' => '1x1',
                                'css' => 'photo',
                                'url' => $thumUrl
                            ));
                            ?>
                        </a>
                    <?php } ?>
                <?php } ?>
            </div>
            <?php } ?>
        </div>
    </div>
    
    <div class="hidden-md-up">
        <?php if (!empty($list_variant)) { ?>
            <?php
                $defaultImage = $this->info['image'];
                foreach ($list_variant as $index => $variant) {
                    $variantId = $variant['id'];
                    $variantThumbs = isset($thumbs[$variantId]) ? $thumbs[$variantId] : [$defaultImage];
                    $class = ($index === 0) ? 'variant-image' : 'variants-image';
            ?>
                    <input type="hidden" class="<?= $class ?>" data-id="<?= $variantId ?>" value='<?php echo json_encode($variantThumbs) ?>'>
            <?php
                }
            ?>
        <?php } else {?>
            <?php if (!empty($thumbs_color)) { ?>
                <input type="hidden" class="color-image" data-id="1" value='<?php echo json_encode($thumbs_color)?>'>
            <?php } ?>
        <?php }?>

        <ul id="productMobilePhotos" class="mobile">
            <?php if (!empty($list_variant)) { ?>
                <?php foreach ($list_variant as $variant) { ?>
                    <?php $variant_images = $thumbs[$variant['id']];?>
                    <?php if(!empty($variant_images)){?>
                        <?php foreach ($variant_images as $key => $value) { ?>
                            <?php $thumbClass = ($variant['id'] == $list_variant[0]['id'] && $key == 0) ? 'active' : ''; ?>
                            <?php $thumUrl = PHOTO_PATH . $value; ?> 
                            <a class="<?php //echo $thumbClass ?> image_thumbs variant_<?php echo $variant['id'] ?>" 
                            data-image="<?php echo $thumUrl ?>"
                            data-index="<?php echo $key ?>"
                            data-zoom-image="<?php echo $thumUrl ?>"
                            >
                            <?php
                            echo $this->partial('/shared/_lazy_image.phtml', array(
                                'ratio' => '6x4',
                                'css' => 'photo',
                                'url' => $thumUrl
                            ));
                            ?>
                            </a>
                        <?php } ?>
                    <?php } else { ?>
                        <?php $defaultImage = PHOTO_PATH . $this->info['image'];?>
                        <a class="image_thumbs variant_<?php echo $variant['id'] ?>" 
                            data-image="<?php echo $defaultImage ?>"
                            data-index="0"
                            data-zoom-image="<?php echo $defaultImage ?>"
                        >
                            <?php
                            echo $this->partial('/shared/_lazy_image.phtml', array(
                                'ratio' => '6x4',
                                'css' => 'photo',
                                'url' => $defaultImage
                            ));
                            ?>
                        </a>
                    <?php } ?>   
                <?php } ?>
            <?php } ?>
            <?php if (empty($thumbs_color) == false) { ?>
                <?php foreach ($thumbs_color as $key => $value) { ?>
                    <?php $thumbClass = ($key == 0) ? 'active' : ''; ?>
                    <?php $thumUrl = PHOTO_PATH . $value; ?>
                    <a class="<?php //echo $thumbClass ?> image_thumbs color_<?php echo (empty($color_index) == true ) ? 1: $color_index[$key]?>" 
                    data-image="<?php echo $thumUrl ?>"
                    data-index="<?php echo $key ?>"
                    data-zoom-image="<?php echo $thumUrl ?>" 
                    >
                        <?php
                        echo $this->partial('/shared/_lazy_image.phtml', array(
                            'ratio' => '6x4',
                            'css' => 'photo',
                            'url' => $thumUrl
                        ));
                        ?>
                    </a>
                <?php } ?>
            <?php } ?>
        </ul>
        <div class="custom-dots"></div>
        <div class="slide-small">
            <div id="productMobilePhotosSmall" style ="margin-top:20px" class="mobile-small">
                <?php if (!empty($list_variant)) { ?>
                    <?php foreach ($list_variant as $variant) { ?>
                        <?php $variant_images = $thumbs[$variant['id']];?>
                        <?php if(empty($variant_images)==false){?>
                            <?php foreach ($variant_images as $key => $value) { ?>
                                <?php $thumbClass = ($variant['id'] == $list_variant[0]['id'] && $key == 0) ? 'active' : ''; ?>
                                <?php $thumUrl = PHOTO_PATH . $value; ?> 
                                <a class="<?php //echo $thumbClass ?> image_thumbs_small variant_<?php echo $variant['id'] ?>" 
                                data-image="<?php echo $thumUrl ?>"
                                data-index="<?php echo $key ?>"
                                data-zoom-image="<?php echo $thumUrl ?>"
                                >
                                <?php
                                echo $this->partial('/shared/_lazy_image.phtml', array(
                                    'ratio' => '6x4',
                                    'css' => 'photo',
                                    'url' => $thumUrl
                                ));
                                ?>
                            </a>
                            <?php } ?>
                        <?php }else { ?>
                            <?php $defaultImage = PHOTO_PATH . $this->info['image'];?>
                            <a class="image_thumbs variant_<?php echo $variant['id'] ?>" 
                                data-image="<?php echo $defaultImage ?>"
                                data-index="0"
                                data-zoom-image="<?php echo $defaultImage ?>"
                            >
                                <?php
                                echo $this->partial('/shared/_lazy_image.phtml', array(
                                    'ratio' => '6x4',
                                    'css' => 'photo',
                                    'url' => $defaultImage
                                ));
                                ?>
                            </a>
                        <?php } ?>    
                    <?php } ?>
                <?php } else { ?>
                    <?php if (empty($thumbs_color) == false) { ?>
                        <?php foreach ($thumbs_color as $key => $value) { ?>
                            <?php $thumbClass = ($key == 0) ? 'active' : ''; ?>
                            <?php $thumUrl = PHOTO_PATH . $value; ?>
                            <a class="<?php //echo $thumbClass ?> image_thumbs_small color_<?php echo (empty($color_index) == true ) ? 1: $color_index[$key]?>" 
                            data-image="<?php echo $thumUrl ?>"
                            data-index="<?php echo $key ?>"
                            data-zoom-image="<?php echo $thumUrl ?>" 
                            >
                                <?php
                                echo $this->partial('/shared/_lazy_image.phtml', array(
                                    'ratio' => '6x4',
                                    'css' => 'photo',
                                    'url' => $thumUrl
                                ));
                                ?>
                            </a>
                        <?php } ?>
                    <?php } ?>
                <?php }?>

            </div>
            <span id="custom-prev" class="custom-arrow"></span>
            <span id="custom-next" class="custom-arrow"></span>
        </div>
    </div>
</div>

<style>
    .zoomWrapper{
        position: relative;
        width:100%!important;
    }
    #click-left, #click-left-smp {
        position: absolute;
        top: calc(50% - 32px);
        outline: 0;
        left: 16px;
        width: 32px;
        height: 32px;
        text-indent: -9999px;
        z-index: 999;
    }
    .btn-prev{
        left: 10px;
        background: url(../img/bxslider/controls.png) no-repeat 0 -32px;
    }
    .btn-next{
        right: 10px;
        background: url(../img/bxslider/controls.png) no-repeat -43px -32px;
    }
    
    #click-right, #click-right-smp {
        position: absolute;
        top: calc(50% - 32px);
        right: 16px;
        outline: 0;
        width: 32px;
        height: 32px;
        text-indent: -9999px;
        z-index: 999;
    }
    #click-right, #click-left:hover {
        cursor: pointer;
    }
    .custom-dots  {
        display: flex;
        margin: auto;
    }
    .custom-dots .slick-dots {
        margin: auto;
        display: flex;
        margin: auto;
        align-items: center;
    }
    .custom-dots .slick-dots li  {
        display: block;
        width: 10px;
        height: 10px;
        background: gray;
        border-radius: 50%;
        margin: 3px;
    }
    .custom-dots .slick-dots li button {
        display: none;
    }
    .custom-dots .slick-dots li.slick-active{
        background-color: black;
    }
    .image_detail:hover {
        cursor: url('../img/bxslider/icons-earch-plus.png'), auto;
    }
    @media (max-width: 768px) {
        .hidden-xs-down {
            display: none !important;
        }
        .slide-small {
            position: relative;
        }

        .custom-arrow {
            position: absolute;
            top: 50%;
            transform: translateY(-50%);
            z-index: 1000;
            background-color: rgba(0, 0, 0, 0.5);
            color: white;
            width: 32px;
            height: 32px;
            border-radius: 50%;
            display: flex;
            justify-content: center; 
            align-items: center; 
        }

        #custom-prev {
            left: -10px;
            background: url(../img/bxslider/controls.png) no-repeat 0 -32px;
        }

        #custom-next {
            right: -10px;
            background: url(../img/bxslider/controls.png) no-repeat -43px -32px;
        }

    }
</style>