<div class="purchase">
    <form id="purc_frm" name="purc_frm" method="POST">
        <ul class="qty">
            <li>
                <a id="minus" style="cursor: pointer"><i class="fa fa-minus"></i></a>
            </li>
            <?php
                if(isset($this->info["quanti_limit"]) && !empty($this->info["quanti_limit"])){?>
                    <li>
                        <input type="tel" readonly min="1" max="<?php echo $this->info["quanti_limit"] ?>" value="1" id="number"/>
                    </li>
                <?php } else { ?>
                    <li>
                        <input type="tel" readonly min="1" max="100" value="1" id="number"/>
                    </li>
                <?php }
            ?>
            <li>
                <a id="plus" style="cursor: pointer"><i class="fa fa-plus"></i></a>
            </li>
        </ul>
        <button class="btn-cart" id="add_to_cart">
            <i class="fa fa-cart-plus"></i>
            <span>Thêm vào giỏ</span>
        </button>
        <input type="hidden" id="quanti_limit" value="<?php echo $this->info["quanti_limit"]?>" name="quanti_limit"/>
        <input type="hidden" id="pid" name="pid" value="<?php echo $this->info["id"]?>"/>
        <input type="hidden" id="qty" name="qty"/>
        <input type="hidden" id="t" name="t"/>
        <input type="hidden" id="color" name="color" value="<?php echo !empty($this->color_list[0]['id']) ? $this->color_list[0]['id']:'1'?>" />
        <input type="hidden" id="variant" name="variant" value="<?php echo !empty($this->list_variant[0]['id']) ? $this->list_variant[0]['id']:''?>" />
        <input type="hidden" id="combo_id" name="combo_id" value="<?php echo !empty($this->combo_product['id']) ? $this->combo_product['id']:''?>" />
    </form>
</div>