<div class="specs">
    <table class="table-bordered">
        <thead>
            <tr>
                <td colspan="2">
                    <strong>Thông tin game</strong>
                </td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Thể loại</td>
                <td>Action Adventure</td>
            </tr>
            <tr>
                <td>Hệ máy</td>
                <td>Nintendo Switch, Nintendo 3DS</td>
            </tr>
            <tr>
                <td>ESRB</td>
                <td>Everyone 10+ Fantasy Violence, Mild Suggestive Themes, Use of Alcohol</td>
            </tr>
            <tr>
                <td>Ngày phát hành</td>
                <td>3/3/2017</td>
            </tr>
            <tr>
                <td>Nhà sản xuất &amp; phát hành</td>
                <td>Nintendo</td>
            </tr>
        </tbody>
    </table>
</div>
