<div class="side-box category-menu">
	<?php if( empty($this->title) == false ){ ?>
    	<header><?php echo $this->title ?></header>
    <?php } ?>
    <ul>    
        <?php if (empty($this->data[0]) == false && is_array($this->data[0])) { ?>
            <?php foreach ($this->data[0] as $key0 => $value0) { ?>
                <li class="item-<?php echo $key0+1?>">
                    <a href="/danh-muc/<?php echo $value0['url_slug'] ?>">
                    	<span class="icon">
                    		<?php if( empty($value0['icon']) == false && empty($value0['icon_hover']) == false ) { ?>
			                    <img class="state-1" src="<?php echo PHOTO_PATH.$value0['icon'];?>" width="24" height="24" />
			                    <img class="state-2" src="<?php echo PHOTO_PATH.$value0['icon_hover'];?>" width="24" height="24" />
		                    <?php }?>
		                </span>
                        <span> <?php echo $value0['name'] ?></span>
                        <i class="fa fa-caret-right"></i>
                    </a>
                    <ul>
                        <?php if (empty($this->data[1]) == false && is_array($this->data[1])) { ?>
                            <?php foreach ($this->data[1] as $key1 => $value1) { ?>
                                <?php if ($value1['parent_category'] == $value0['id']) { ?>
                                    <li class="item-<?php echo $key0+1?>">
                                        <a href="/danh-muc/<?php echo $value1['url_slug'] ?>">
                                            <span> <?php echo $value1['name'] ?></span>
                                            <i class="fa fa-caret-right"></i>
                                        </a>
                                        <ul>
                                            <?php if (empty($this->data[2]) == false && is_array($this->data[2])) { ?>
                                                <?php foreach ($this->data[2] as $key2 => $value2) { ?>
                                                    <?php if ($value2['parent_category'] == $value1['id']) { ?>
                                                        <li class="item-<?php echo $key0+1?>">
                                                            <a href="/danh-muc/<?php echo $value2['url_slug'] ?>">
                                                               <span> <?php echo $value2['name'] ?></span>
                                                            </a>
                                                        </li>
                                                    <?php } ?>
                                                <?php } ?>
                                            <?php } ?>
                                        </ul>
                                    </li>
                                <?php } ?>
                            <?php } ?>
                        <?php } ?>
                    </ul>
                </li>
            <?php } ?>
        <?php } ?>
    </ul>
</div>
