<div class="category-item">
    <a class="avatar" href="<?php echo $this->url ?>">
        <?php echo $this->partial('/shared/_lazy_image.phtml', array(
            'ratio' => '1x1',
            'css' => 'photo',
            'url' => $this->photo,
        )) ?>
    </a>
    <div class="detail">
        <div class="name">
            <a href="<?php echo $this->url ?>"><?php echo $this->name ?></a>
        </div>
    </div>
</div>
<style>
    ul.grid .category-item {
    border: 0px;
    width: 50%;
    margin-left: 10%;
    margin-right: 10%;
}
@media screen and (max-width: 767px){
        ul.grid .category-item{
            width: 70%;
        }
}
</style>


