<?php
    $this->qcss = $this->qcss . isset($this->description) ? ' has-dd' : '';
?>
<header class="data-header <?php echo $this->qcss ?>">
    <?php echo $this->title ?>
</header>
<?php if(isset($this->description)) {
    echo "<div class='data-description'>$this->description</div>";
}?>

<style>
    .data-description div img {
        width: calc(100% + 3rem)!important;
        margin-left:-1.5rem;
    }
    .data-description span img {
        width: calc(100% + 3rem)!important;
        margin-left:-1.5rem;
    }
/* @media (min-width: 768px) and (max-width: 991px){
    .data-description div a img {
        width: calc(100% + 3rem)!important;
        margin-left:-1.5rem;
    }
    .data-description div span img {
        width: calc(100% + 3rem)!important;
        margin-left:-1.5rem;
    }
    .data-description div img {
        width: calc(100% + 3rem)!important;
        margin-left:-1.5rem;
    }
}
@media screen and (max-width: 767px){
    .data-description div a img {
        width: calc(100% + 3rem)!important;
        margin-left:-1.5rem;
    }
    .data-description div span img {
        width: calc(100% + 3rem)!important;
        margin-left:-1.5rem;
    }
    .data-description div img {
        width: calc(100% + 3rem)!important;
        margin-left:-1.5rem;
    }
}

@media screen and (max-width: 480px){
    .data-description div a img {
        width: calc(100% + 3rem)!important;
        margin-left:-1.5rem;
    }
     .data-description div span img {
        width: calc(100% + 3rem)!important;
        margin-left:-1.5rem;
    }
    .data-description div img {
        width: calc(100% + 3rem)!important;
        margin-left:-1.5rem;
    }
    
} */
</style>
