<div class="menu-pc hidden-mobile">
    <?php
        if( empty( $this->menuCategory) == false ){
            echo $this->partial('/shared/_category_menu.phtml', array(
                'title' => 'Danh mục', 'data' => $this->menuCategory
            ));
        }
    ?>
</div>
<?php
if (isset($this->listCategoryPost) && empty($this->listCategoryPost) == false) {
    echo $this->partial('/pages/_category.phtml', array(
        'title' => 'Danh mục', 'data' => $this->listCategoryPost
    ));
}
?>
<div class="hidden-md-down">
    <?php
    // if (empty($this->productBestSell) == false) {
    //     echo $this->partial('/shared/_product_menu.phtml', array(
    //         'title' => 'Bán chạy',
    //         'data' => $this->productBestSell
    //     ));
    // }
    ?>

    <?php
    if (empty($this->newProducts) == false) {
        echo $this->partial('/shared/_product_menu.phtml', array(
            'title' => 'Mới cập nhật',
            'data' => $this->newProducts
        ));
    }
    ?>

    <?php
    if (empty($this->newestPostMenu) == false) {
        $top = $this->newestPostMenu[0];
        unset($this->newestPostMenu[0]);
        echo $this->partial('/shared/_post_menu.phtml', array(
            'title' => 'Tin tức mới',
            'top' => $top,
            'data' => $this->newestPostMenu
        ));
    }
    ?>
</div>
<style>
    @media screen and (min-width: 768px){
        .hidden-mobile{
            display: block;
        }
    }
    @media screen and (max-width: 767px){
        .hidden-mobile{
            display: none;
        }
    }
</style>