<?php
    $css = isset($this->css) ? $this->css : 'mobile-menu';
?>
<aside class="<?php echo $css ?>">
    <nav>
        <ul>
            <li>
                <a href="/">Trang chủ</a>
            </li>
        </ul>
        <?php
            if( empty( $this->menuCategory) == false ){
                echo $this->partial('/shared/_category_menu_mobile.phtml', array(
                    'title' => 'Danh mục', 'data' => $this->menuCategory
                ));
            }
        ?>
        <ul>
            <?php
            foreach ($this->menu as $key => $value) {
                if (empty($value['child']) == true) {
                    ?>
                    <li>
                        <?php
                            $flash = '/';
                            $url = parse_url($value['url']);
                            if ($url['scheme'] == 'http' || $url['scheme'] == 'https') {
                                $flash = '';
                            }
                        ?>
                        <a href="<?php echo $flash . $value['url'] ?>"><?php echo $value['name'] ?></a>
                    </li>
                    <?php
                } 
            }
            ?>
        </ul>
    </nav>
    <div class="overlay"></div>
</aside>

<style>
    .mobile-menu nav {
        width: 85vw;
        height: 100%;
        overflow: auto;
        background: #e4e4e4;
        display: block;
        z-index: 2;
        position: absolute;
        top: 0;
        left: -85vw;
    }
    .mobile-menu nav>ul li a {
        display: block;
        padding: 10px;
        font-size: 1.1rem;
        color: #444;
        padding-left: 2.25rem;
        text-transform: uppercase;
        border-bottom: 1px solid #cbcbcb;
    }
    .mobile-menu nav>ul:last-of-type {
        margin-top: 0;
        border-top: 0;
    }
</style>
