<?php
    $css = isset($this->css) ? $this->css : 'mobile-menu';
?>
<aside class="<?php echo $css ?>">
    <nav>
        <ul>
            <li>
                <a href="/">Trang chủ</a>
            </li>
        </ul>
        <?php
            if( empty( $this->menuCategory) == false ){
                echo $this->partial('/shared/_category_menu_mobile.phtml', array(
                    'title' => 'Danh mục', 'data' => $this->menuCategory
                ));
            }
        ?>
        <ul>
            <?php
            foreach ($this->menu as $key => $value) {
                if (empty($value['child']) == true) {
                    ?>
                    <li>
                        <?php
                            $flash = '/';
                            $url = parse_url($value['url']);
                            if ($url['scheme'] == 'http' || $url['scheme'] == 'https') {
                                $flash = '';
                            }
                        ?>
                        <a href="<?php echo $flash . $value['url'] ?>"><?php echo $value['name'] ?></a>
                    </li>
                    <?php
                } 
            }
            ?>
        </ul>
    </nav>
    <div class="overlay"></div>
</aside>
