
<?php 
$now = date('Y-m-d H:i:s');
if ($now <= $this->count_down && $now >= $this->count_time_start && $this->status_flash_sale == 1) {
?>
    <div class="product-item product_<?php echo $this->id ?>" attr-id="<?php echo $this->id ?>" attr-count-down="<?php echo $this->count_down ?>" attr-enable-promo="<?php echo $this->status_flash_sale ?>">   
<?php 
} else {
?>
    <div class="product-item product_<?php echo $this->id ?>" attr-id="<?php echo $this->id ?>" attr-count-down="" attr-enable-promo="">
<?php 
}
?>

   <a class="avatar" href="<?php echo $this->url?>">
      <?php
         echo $this->partial ( '/shared/_lazy_image.phtml', array (
         										'ratio' => '1x1',
         										'css' => 'photo',
         										'url' => $this->photo 
         								) )?>
      <?php
      if($now <= $this->count_down && $now >= $this->count_time_start && $this->status_flash_sale ==1) {?>
         <div class="label-a" style="color:<?php echo $this->percent_flash_sale ['tcolor']?>;background:<?php echo $this->percent_flash_sale ['bcolor']?>">
            <span><?php echo $this->percent_flash_sale ['text']?></span>
         </div>
      <?php }else{?>
         <div class="label-a" style="color:<?php echo $this->labelA ['tcolor']?>;background:<?php echo $this->labelA ['bcolor']?>">
            <span><?php echo $this->labelA ['text']?></span>
         </div>
      <?php }?>

      <?php
         if (empty ( $this->labelB ['text'] [0] ) == false && $now <= $this->count_down && $now >= $this->count_time_start && $this->status_flash_sale ==1) {
      ?>
         <div class="label-b label-text" style="color:<?php echo $this->labelB ['tcolor']?>;background:<?php echo $this->labelB ['bcolor']?>">
            <div class="rotator">
               <?php for($x = 0; $x < count ( $this->labelB ['text'] ); $x ++) { ?>
               <span><?php echo $this->labelB ['text'] [$x]?></span>
               <?php } ?>
            </div>
         </div>
      <?php }elseif(empty ( $this->labelB ['text'] [0] ) == false) {?>
         <div class="label-b label-text" style="color:<?php echo $this->labelB ['tcolor']?>;background:<?php echo $this->labelB ['bcolor']?>">
            <div class="rotator">
               <?php for($x = 0; $x < count ( $this->labelB ['text'] ); $x ++) { ?>
               <span><?php echo $this->labelB ['text'] [$x]?></span>
               <?php } ?>
            </div>
         </div>
      <?php }?>
   </a>
   <div class="detail">
      <div class="name">
         <a href="<?php echo $this->url?>"><?php echo $this->name?></a>
      </div>
      <?php
      if($this->priceB && $this->priceB==0){?>
          <div class="price" style="display:none"></div>
      <?php }else{?>
         <div class="price">
            <?php
               $now = date('Y-m-d H:i:s');
               $priceflashSale = isset($this->priceC) ? substr($this->priceC, 0, 1) : '';
               if ($now <= $this->count_down && $now >= $this->count_time_start && $this->status_flash_sale == 1 && $this->priceC > 0) {
                  echo '<span class="price-a">' . $this->priceC . '</span>';
                  echo '<span class="price-b" style="color:black">' . $this->priceB . '</span>';
               } elseif ((strtotime($this->count_time_start)-strtotime($now)) > 0 &&  (strtotime($this->count_time_start)-strtotime($now)) <= 6 * 3600) {
                  echo '<span class="price-a">' . $priceflashSale . '?????&#8363;</span>';
                  echo '<span class="price-b" style="color:black">' . $this->priceB . '</span>';
               } else {
                  if ((isset($this->priceB) && $this->priceB == $this->priceA)) {
                     echo '<span class="price-a">' . $this->priceA . '</span>';
               } elseif (isset($this->priceB) && $this->priceB != $this->priceA) {
                     echo '<span class="price-a">' . $this->priceA . '</span>';
                     echo '<span class="price-b" style="color:black">' . $this->priceB . '</span>';
               }
               }
            ?>
         </div>
      <?php }?>
      
   </div>
   <?php if ($this->priceA > 0 && $this->status != STATUS_IN_OUT_STOCK) { ?>
   <!-- <a class="btn cart cart_btn my_btn" href="<?php echo $this->cart?>" pid="<?php echo $this->id?>" qty="1">
  	   <i class="fa fa-cart-plus"></i> Thêm vào giỏ
   </a> -->
   <?php }elseif($this->priceA==0){ ?>
   <a class="btn btn-danger my_btn" href="tel:+84906221218">
    Liên hệ
   </a>
   <?php }else {?>
   <!-- <a class="btn btn-danger my_btn" href="tel:+84906221218">
    Tạm hết hàng
   </a> -->
   <?php }?>
</div>
<style>
   ul.grid .category-item .detail .name a, ul.grid .product-item .detail .name a, ul.slider .category-item .detail .name a, ul.slider .product-item .detail .name a {
      margin: auto;
      display: block;
      font-weight: bold;
      color: #222;
   }
    @media screen and (min-width: 768px){

    }
    @media screen and (max-width: 767px){
      ul.grid .category-item .detail .name a, ul.grid .product-item .detail .name a, ul.slider .category-item .detail .name a, ul.slider .product-item .detail .name a {
         font-size: 14px!important;
         display: -webkit-box;
         -webkit-box-orient: vertical;
         -webkit-line-clamp: 3;
         overflow: hidden;
         text-overflow: ellipsis;
         white-space: normal;
      }
      /* .count_down_container.label-b {
         font-size: 1rem !important;
      } */
      ul.grid .product-item .avatar .label-a, ul.slider .product-item .avatar .label-a {
         border-radius: inherit;
         font-size: 14px!important;
      }
      ul.grid .product-item .avatar .label-a, ul.slider .product-item .avatar .label-a {
         border-radius: .2rem;
         display: block;
         z-index: 2;
         position: absolute;
         top: 0!important;
         right:0!important;
      }
    }
</style>