<div class="product-item product_<?php echo $this->id ?>" attr-id="<?php echo $this->id ?>" attr-count-down="<?php echo $this->count_down?>" attr-enable-promo="<?php echo $this->enable_promo?>">
   <a class="avatar" href="<?php echo $this->url?>">
      <?php
         echo $this->partial ( '/shared/_lazy_image.phtml', array (
         										'ratio' => '1x1',
         										'css' => 'photo',
         										'url' => $this->photo 
         								) )?>
      <div class="label-a" style="color:<?php echo $this->labelA ['tcolor']?>;background:<?php echo $this->labelA ['bcolor']?>">
         <span><?php echo $this->labelA ['text']?></span>
      </div>
      <?php
         if (empty ( $this->labelB ['text'] [0] ) == false) {
      ?>
      <div class="label-b label-text" style="color:<?php echo $this->labelB ['tcolor']?>;background:<?php echo $this->labelB ['bcolor']?>">
         <div class="rotator">
            <?php for($x = 0; $x < count ( $this->labelB ['text'] ); $x ++) { ?>
            <span><?php echo $this->labelB ['text'] [$x]?></span>
            <?php } ?>
         </div>
      </div>
      <?php } ?>
   </a>
   <div class="detail">
      <div class="name">
         <a href="<?php echo $this->url?>"><?php echo $this->name?></a>
      </div>
      <div class="price">
         <span class="price-a">
         <?php
            if ($this->priceA > 0) {
            	echo $this->priceA;
            }
            // else {
            // 	echo 'Liên Hệ';
            // } 
         ?>
         </span>
         <?php if (isset ( $this->priceB ) && $this->priceB != $this->priceA) { ?>
         <span class="price-b"> <?php echo $this->priceB?></span>
         <?php } ?>
      </div>
   </div>
   <?php if ($this->priceA > 0 && $this->status != STATUS_IN_OUT_STOCK) { ?>
   <a class="btn cart cart_btn my_btn" href="<?php echo $this->cart?>" pid="<?php echo $this->id?>" qty="1">
  	   <i class="fa fa-cart-plus"></i> Thêm vào giỏ
   </a>
   <?php }elseif($this->priceA==0){ ?>
   <a class="btn btn-danger my_btn" href="tel:+84906221218">
    Liên hệ
   </a>
   <?php }else {?>
   <a class="btn btn-danger my_btn" href="tel:+84906221218">
    Tạm hết hàng
   </a>
   <?php }?>
</div>
<style>
   ul.slider .product-item .detail .price .price-a {
      font-weight: bold;
      color: #dc2535;
   }

   ul.slider .product-item .detail .price .price-b {
      font-size: 1.2rem;
      margin-left: 0.2rem;
      text-decoration: line-through;
   }

   @media screen and (max-width: 480px) {
      ul.slider .product-item .detail .price .price-a {
         font-size: 1rem;
      }

      ul.slider .product-item .detail .price .price-b {
         font-size: 0.8rem;
      }
   }

   @media screen and (min-width: 481px) and (max-width: 768px) {
      ul.slider .product-item .detail .price .price-a{
         font-size: 1.1rem;
      }
      ul.slider .product-item .detail .price .price-b {
         font-size: 1rem;
      }
   }

   @media screen and (min-width: 769px) {
      ul.slider .product-item .detail .price .price-a{
         font-size: 1.3rem;
      }
      ul.slider .product-item .detail .price .price-b {
         font-size: 1.2rem;
      }
   }

</style>