<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title"> <i class="icon-home4 position-left"></i> <?php echo $this->translate('home') ?></h5>
    </div>
</div>
<div class="content home-content">
    <div class="col-md-3 margin-bottom">
        <div class="col-xs-12">
            <button class="btn bg-violet btn-float btn-float-lg btn-block" onclick="window.location = 'http://<?php echo $_SERVER['SERVER_NAME'] ?>'" type="button">
                <span>&nbsp;</span><i class="fa fa-home"></i> <span>TRANG CHỦ</span>
            </button>
        </div>
    </div>
    <?php if (UtilAuth::hasPrivilege('product', ACTION_VIEW) == true || UtilAuth::hasPrivilege('product', ACTION_ADD) == true || UtilAuth::hasPrivilege('product', ACTION_EDIT) == true) { ?>
        <div class="col-md-3 margin-bottom">
            <div class="col-xs-12">
                <button class="btn bg-danger btn-float btn-float-lg btn-block" onclick="window.location = '/admin/product'" type="button">
                    <span>&nbsp;</span><i class="fa fa-gamepad"></i> <span>SẢN PHẨM</span>
                </button>
            </div>
        </div>
    <?php } ?>

    <?php if (UtilAuth::hasPrivilege('category', ACTION_VIEW) == true || UtilAuth::hasPrivilege('category', ACTION_ADD) == true || UtilAuth::hasPrivilege('category', ACTION_EDIT) == true) { ?>
        <div class="col-md-3 margin-bottom">
            <div class="col-xs-12">
                <button class="btn bg-purple-300 btn-float btn-float-lg btn-block" onclick="window.location = '/admin/category'" type="button">
                    <span>&nbsp;</span><i class="fa fa-server"></i> <span>DANH MỤC</span>
                </button>
            </div>
        </div>
    <?php } ?>
    <?php if (UtilAuth::hasPrivilege('promotion-code', ACTION_VIEW) == true || UtilAuth::hasPrivilege('promotion-code', ACTION_ADD) == true || UtilAuth::hasPrivilege('promotion-code', ACTION_EDIT) == true) { ?>
        <div class="col-md-3 margin-bottom">
            <div class="col-xs-12">
                <button class="btn bg-teal-400 btn-float btn-float-lg btn-block" onclick="window.location = '/admin/promotion-code'" type="button">
                    <span>&nbsp;</span><i class="fa fa-bookmark-o"></i> <span>MÃ KHUYẾN MÃI</span>
                </button>
            </div>
        </div>
    <?php } ?>
    <?php if (UtilAuth::hasPrivilege('order', ACTION_VIEW) == true || UtilAuth::hasPrivilege('order', ACTION_ADD) == true || UtilAuth::hasPrivilege('order', ACTION_EDIT) == true) { ?>
        <div class="col-md-3 margin-bottom">
            <div class="col-xs-12">
                <button class="btn bg-warning btn-float btn-float-lg btn-block" onclick="window.location = '/admin/order'" type="button">
                    <span>&nbsp;</span><i class="fa fa-calendar-o"></i> <span>ĐƠN HÀNG</span>
                </button>
            </div>
        </div>
    <?php } ?>

    <?php if (UtilAuth::hasPrivilege('menu', ACTION_VIEW) == true || UtilAuth::hasPrivilege('menu', ACTION_ADD) == true || UtilAuth::hasPrivilege('menu', ACTION_EDIT) == true) { ?>
        <div class="col-md-3 margin-bottom">
            <div class="col-xs-12">
                <button class="btn bg-blue btn-float btn-float-lg btn-block" onclick="window.location = '/admin/menu'" type="button">
                    <span>&nbsp;</span><i class="fa fa-bars"></i> <span>MENU</span>
                </button>
            </div>
        </div>
    <?php } ?>

    <?php if (UtilAuth::hasPrivilege('banner', ACTION_VIEW) == true || UtilAuth::hasPrivilege('banner', ACTION_ADD) == true || UtilAuth::hasPrivilege('banner', ACTION_EDIT) == true) { ?>
        <div class="col-md-3 margin-bottom">
            <div class="col-xs-12">
                <button class="btn bg-brown-300 btn-float btn-float-lg btn-block" onclick="window.location = '/admin/banner'" type="button">
                    <span>&nbsp;</span><i class="fa fa-film"></i> <span>BANNER</span>
                </button>
            </div>
        </div>
    <?php } ?>
    <?php if (UtilAuth::hasPrivilege('media', ACTION_VIEW) == true || UtilAuth::hasPrivilege('media', ACTION_ADD) == true || UtilAuth::hasPrivilege('media', ACTION_EDIT) == true) { ?>
        <div class="col-md-3 margin-bottom">
            <div class="col-xs-12">
                <button class="btn bg-green btn-float btn-float-lg btn-block" onclick="window.location = '/admin/media'" type="button">
                    <span>&nbsp;</span><i class="fa fa-picture-o"></i> <span>THƯ VIỆN ẢNH</span>
                </button>
            </div>
        </div>
    <?php } ?>
    <?php if (UtilAuth::hasPrivilege('setting', ACTION_VIEW) == true || UtilAuth::hasPrivilege('setting', ACTION_ADD) == true || UtilAuth::hasPrivilege('setting', ACTION_EDIT) == true) { ?>
        <div class="col-md-3 margin-bottom">
            <div class="col-xs-12">
                <button class="btn bg-orange btn-float btn-float-lg btn-block" onclick="window.location = '/admin/setting'" type="button">
                    <span>&nbsp;</span><i class="fa fa-cog"></i> <span>CÀI ĐẶT</span>
                </button>
            </div>
        </div>
    <?php } ?>
    <?php if (UtilAuth::hasPrivilege('post', ACTION_VIEW) == true || UtilAuth::hasPrivilege('post', ACTION_ADD) == true || UtilAuth::hasPrivilege('post', ACTION_EDIT) == true) { ?>
        <div class="col-md-3 margin-bottom">
            <div class="col-xs-12">
                <button class="btn bg-pink-300 btn-float btn-float-lg btn-block" onclick="window.location = '/admin/post'" type="button">
                    <span>&nbsp;</span><i class="fa fa-pencil-square-o"></i> <span>BÀI VIẾT</span>
                </button>
            </div>
        </div>
    <?php } ?>
    <?php if (UtilAuth::hasPrivilege('user', ACTION_VIEW) == true || UtilAuth::hasPrivilege('user', ACTION_ADD) == true || UtilAuth::hasPrivilege('user', ACTION_EDIT) == true) { ?>
        <div class="col-md-3 margin-bottom">
            <div class="col-xs-12">
                <button class="btn bg-slate-300 btn-float btn-float-lg btn-block" onclick="window.location = '/admin/user'" type="button">
                    <span>&nbsp;</span><i class="fa fa-user"></i> <span>NGƯỜI DÙNG</span>
                </button>
            </div>
        </div>
    <?php } ?>
    <?php if (UtilAuth::hasPrivilege('permission', ACTION_VIEW) == true || UtilAuth::hasPrivilege('permission', ACTION_ADD) == true || UtilAuth::hasPrivilege('permission', ACTION_EDIT) == true) { ?>
        <div class="col-md-3 margin-bottom">
            <div class="col-xs-12">
                <button class="btn bg-warning-800 btn-float btn-float-lg btn-block" onclick="window.location = '/admin/permission'" type="button">
                    <span>&nbsp;</span><i class="fa fa-users"></i> <span>PHÂN QUYỀN</span>
                </button>
            </div>
        </div>
    <?php } ?>
    <?php
    if (UtilAuth::hasPrivilege('statistic', ACTION_VIEW) == true || UtilAuth::hasPrivilege('statistic', ACTION_ADD) == true || UtilAuth::hasPrivilege('statistic', ACTION_EDIT) == true) {
        ?>
        <div class="col-md-3 margin-bottom">
            <div class="col-xs-12">
                <button class="btn bg-primary-300 btn-float btn-float-lg btn-block" onclick="window.location = '/admin/statistic'" type="button">
                    <span>&nbsp;</span><i class="icon-file-stats"></i> <span>THỐNG KÊ</span>
                </button>
            </div>
        </div>
    <?php } ?>
</div>