<form id="change-password-form" class="form-validate-jquery" name="change-password-form">
    <div class="content-divider text-muted form-group"><span><?php echo $this->translate('your-credentials') ?></span></div>
    <div class="form-group has-feedback has-feedback-left">
        <input type="password" class="form-control" data-msg="<?php echo $this->translate('please-enter-current-password') ?>" placeholder="<?php echo $this->translate('current-password') ?>" name="curent_password" id="curent_password">
        <div class="form-control-feedback">
            <i class="icon-lock2 text-muted"></i>
        </div>
    </div>
    <div class="content-divider text-muted form-group"><span></span></div>
    <div class="form-group has-feedback has-feedback-left">
        <div class="form-group has-feedback has-feedback-left">
            <input type="password" class="form-control" data-msg="<?php echo $this->translate('please-enter-new-password') ?>"placeholder="<?php echo $this->translate('new-password') ?>" 
                   name="new_password" id="new_password">
            <div class="form-control-feedback">
                <i class="icon-user-lock text-muted"></i>
            </div>
        </div>
        <div class="form-group has-feedback has-feedback-left">
            <input type="password" class="form-control" data-msg="<?php echo $this->translate('please-enter-confirm-password') ?>" data-miss-match-msg="<?php echo $this->translate('confirm-new-password-not-correct') ?>"placeholder="<?php echo $this->translate('confirm-new-password') ?>" 
                   name="confirm_new_password" id="confirm_new_password">
            <div class="form-control-feedback">
                <i class="icon-user-lock text-muted"></i>
            </div>
        </div>
        <input type="hidden" value="<?php echo @$this->login_info["user_id"] ?>" name="uId" id="uId"/>
    </div>
</form>