Xin chào <?php echo $this->data ["first_name"] . ' ' . $this->data ["last_name"] ?>,<br>
Bạn vừa yêu cầu đặt lại mật khẩu cho tài khoản của bạn.
Nhấp vào đường dẫn sau để đặt mật khẩu mới:
<?php $link = $_SERVER['SERVER_NAME'].'/auth/reset-password?e=' . $this->data ["email"] . '&t=' . $this->data ["reset_token"] ?>
<a href="<?php echo $link ?> " ><?php echo $link ?></a><br>
Xin cảm ơn, <br>
Herogame Management 
