<!-- Page container -->
<div class="page-container login-container">
    <!-- Page content -->
    <div class="page-content">
        <!-- Main content -->
        <div class="content-wrapper">
            <!-- Content area -->
            <div class="content">
                <!-- Password recovery -->
                <form action="/auth/forgot-password" method="post" id="forgot_password_frm">
                    <div class="panel panel-body login-form">
                        <div class="text-center">
                            <div class="icon-object border-warning text-warning"><i class="icon-spinner11"></i></div>
                            <h5 class="content-group"><?php echo $this->translate('password-recovery') ?> <small class="display-block"><?php echo $this->translate('we-will-send-you-instructions-in-email') ?></small></h5>
                        </div>
                        <?php if (empty($this->message) == false) { ?>
                            <?php
                            $break = false;
                            if (count($this->message) > 1) {
                                $break = true;
                            }
                            ?>
                            <div class="alert <?php echo (isset($this->success) == true) ? 'alert-success' : 'alert-danger' ?> alert-bordered">
                                <button type="button" class="close" data-dismiss="alert"><span>&times;</span><span class="sr-only">Close</span></button>
                                <?php
                                foreach ($this->message as $value) {
                                    echo $value;
                                    if ($break == true)
                                        echo "</br>";
                                }
                                ?>
                            </div>
                        <?php } ?>
                        <div class="form-group has-feedback">
                            <input type="text" class="form-control" data-msg="<?php echo $this->translate('please-enter-username') ?>" placeholder="<?php echo $this->translate('username') ?>" name="f_username" id="f_username">
                            <div class="form-control-feedback">
                                <i class="icon-user text-muted"></i>
                            </div>
                        </div>
                        <div class="form-group has-feedback">
                            <input type="email" class="form-control" placeholder="<?php echo $this->translate('your-email') ?>" name="f_email" id="f_email" data-msg="<?php echo $this->translate('please-enter-email') ?>" data-error-email="<?php echo $this->translate('please-enter-correct-email') ?>">
                            <div class="form-control-feedback">
                                <i class="icon-mail5 text-muted"></i>
                            </div>
                        </div>
                        <button type="submit" class="btn bg-blue btn-block" id="forgot-password-btn"><?php echo $this->translate('reset-password') ?> <i class="icon-arrow-right14 position-right"></i></button>
                    </div>
                </form>
                <!-- /password recovery -->
                <!-- footer -->
                <?php echo $this->render('/partials/_footer.phtml') ?>
                <!-- /footer -->
            </div>
            <!-- /content area -->
        </div>
        <!-- /main content -->
    </div>
    <!-- /page content -->
</div>
<!-- /page container -->