<!-- Page container -->
<div class="page-container login-container">
    <!-- Page content -->
    <div class="page-content">
        <!-- Main content -->
        <div class="content-wrapper">
            <!-- Content area -->
            <div class="content">
                <!-- Password recovery -->
                <form action="/auth/reset-password" method="post" id="reset_password_frm" class="form-validate-jquery" name='reset_password_frm'>
                    <div class="panel panel-body login-form">
                        <div class="text-center">
                            <div class="icon-object border-warning text-warning"><i class="icon-spinner11"></i></div>
                            <h5 class="content-group"><?php echo $this->translate('password-recovery') ?> </h5>
                        </div>
                        <?php if (empty($this->message) == false) { ?>
                            <?php
                            $break = false;
                            if (count($this->message) > 1) {
                                $break = true;
                            }
                            ?>
                            <div class="alert <?php echo (isset($this->success) == true) ? 'alert-success' : 'alert-danger' ?> alert-bordered">
                                <button type="button" class="close" data-dismiss="alert"><span>&times;</span><span class="sr-only">Close</span></button>
                                <?php
                                foreach ($this->message as $value) {
                                    echo $value;
                                    if ($break == true)
                                        echo "</br>";
                                }
                                ?>
                                <?php if( isset($this->success) == true ){?>
                                    <br><?php echo $this->translate('click-here-to-return-login') ?>
                                <?php } ?>
                            </div>
                        <?php } ?>
                        <div class="form-group has-feedback has-feedback-left">
                            <input type="password" class="form-control" data-msg="<?php echo $this->translate('please-enter-new-password') ?>"placeholder="<?php echo $this->translate('new-password') ?>" 
                                   name="r_new_password" id="r_new_password">
                            <div class="form-control-feedback">
                                <i class="icon-user-lock text-muted"></i>
                            </div>
                        </div>
                        <div class="form-group has-feedback has-feedback-left">
                            <input type="password" class="form-control" data-msg="<?php echo $this->translate('please-enter-confirm-password') ?>" data-miss-match-msg="<?php echo $this->translate('confirm-new-password-not-correct') ?>"placeholder="<?php echo $this->translate('confirm-new-password') ?>" 
                                   name="r_confirm_new_password" id="r_confirm_new_password">
                            <div class="form-control-feedback">
                                <i class="icon-user-lock text-muted"></i>
                            </div>
                        </div>
                        <button type="submit" class="btn bg-blue btn-block" id="reset-password-btn"><?php echo $this->translate('reset-password') ?> <i class="icon-arrow-right14 position-right"></i></button>
                    </div>
                    <input type="hidden" value="<?php echo $this->token ?>" name="t" id="t"/>
                    <input type="hidden" value="<?php echo $this->email ?>" name="e" id="e"/>
                </form>
                <!-- /password recovery -->
                <!-- footer -->
                <?php echo $this->render('/partials/_footer.phtml') ?>
                <!-- /footer -->
            </div>
            <!-- /content area -->
        </div>
        <!-- /main content -->
    </div>
    <!-- /page content -->
</div>
<!-- /page container -->