<div class="side-box category-menu">
	<header style="background:red;border-top-left-radius: 10px;border-top-right-radius: 10px;">
	<!-- <?php echo $this->title ?> -->
	Danh mục bài viết
	</header>
	<ul>
		<?php if( empty( $this->data ) == false ){ ?>
		<?php foreach ( $this->data as $cate ){ ?>
		<li class="item-4">
			<a href="/danh-muc-bai-viet/<?php echo $cate['url_slug']?>"> 
				<span class="icon"> </span> 
				<span> <?php echo $cate['name']?></span> 
				<i class="fa fa-caret-right"></i>
			</a>
		</li>
		<?php } ?>
		<?php } ?>
	</ul>
</div>