<?php $this->viewCssClass = 'post detail' ?>
<?php 
	if( empty( $this->info["category-name"] ) == false ){
		$dataBreadcrumbs = array(
            		'parent' => array(
            			'name' =>  @$this->info["category-name"],
            			'url' => '/danh-muc-bai-viet/'.@$this->info["category-url"]
            		),
            		'child' => array(
            			'name' => @$this->info['title']
            		));
	} else {
		$dataBreadcrumbs = array(
				'child' => array(
						'name' => @$this->info['title']
				));
	}
?>
<div class="container">
    <div class="row">
        <div class="col-md-12 hidden-md-down no-gutter">
            <?php echo $this->partial('/shared/_breadcrumbs.phtml',array('data' => $dataBreadcrumbs )) ?>
        </div>
    </div>
    <div class="row">
        <aside class="col-md-2 hidden-mobile">
            <?php echo $this->render("/shared/_left-aside-post.phtml")?>
        </aside>
        <section class="col-md-10 col-12 both-gutter">
            <div class="post-detail">
                <header>
                    <h1><?php echo $this->info['title'] ?></h1>
                    <div class="meta">
                    <?php if( empty( $this->info["category-name"] ) == false ){ ?>
                        <a class="category" href="/danh-muc-bai-viet/<?php echo @$this->info["category-url"] ?>"><?php echo $this->info["category-name"]?></a>,
                        <?php } ?> bởi
                        <a class="author"><?php echo $this->info['created_by'] ?></a>
                        <em class="date">
                            <i class="fa fa-clock-o"></i>
                            <?php echo  UtilFormat::formatTimeForCreatedDate( $this->info['updated_at'], 'd/m/Y H:i:s' ) ?>
                        </em>
                    </div>
                    <div class="react">
                        <div class="share">
                            <div class="sharethis-inline-share-buttons"></div>
                        </div>
                    </div>
                </header>
                <div class="content">
                    <div class="news_if">
                        <?php echo $this->info['content'] ?>  
                    </div>
                </div>
                <?php if( empty( $this->relative_post ) == false ){ ?>
                    <h3 style ="margin-top:20px; margin-bottom:20px;">Bài viết liên quan</h3>
                	<ul class="related post-container">
                		<?php 
                        foreach ( $this->relative_post as $relative ) { ?>
		                    <li class="post-item">
                                <a href="/bai-viet/<?php echo $relative['url_name']?>"> 
                                <div class="post-item-detail">
                                    <div class="post-image-detail" style="width:100%;height: 120px;">
                                        <img class="post-image-detail" src="<?php echo '/upload/images'.'/' . $relative['image_id']; ?>" alt="" width="100%" height="100%" loading="lazy">
                                    </div>
                                    <div class="post-detail" style="padding:0 5px">
                                        <span class="title">
                                            <?php echo $relative['title'] ?>
                                        </span>
                                        <div class="summary-post">
                                            <span class="summary">
                                                <?php echo $relative['summary'] ?>
                                            </span>
                                        </div>
                                        <div class="date">
                                            <?php 
                                                $date = $relative['updated_at'] ? $relative['updated_at'] : $relative['created_at'];
                                                echo 'Ngày:'. date("d/m/Y", strtotime($date));
                                            ?>
                                        </div>

                                    </div>
                                </div>
                                </a> 
		                    </li>
                		<?php } ?>
                	</ul>
                <?php } ?>
                <div class="sp-lien-quan">
                <?php
                if (empty($this->relative_product) == false) {
                    echo $this->partial('/shared/_quick_view.phtml', array(
                        'qdsp' => 'slider',
                        'custom_class' => 'product-relative',
                        'dcol' => 4,
                        'tabs' => array(
                            array(
                                'title' => 'Sản phẩm liên quan',
                                'data' => $this->relative_product
                            )
                        )
                    ));
                }
                ?>
                </div>
                <footer>
                    <?php echo $this->partial('/shared/_data_post_comment.phtml') ?>
                </footer>
            </div>
        </section>
	</div>
</div>
<style>
   .sp-lien-quan ul.nav.nav-tabs {
        display: block!important;
        text-align: center!important;
    }
    .post-container .slick-dots {
 		margin-top: 10px;
		margin: auto;
		display: flex;
        justify-content: center;
	}
	.post-container .slick-dots li {
		display: block;
		width: 10px;
		height: 10px;
		background: gray;
		border-radius: 50%;
		margin: 3px;
	}
	.post-container .slick-dots li button {
		display: none;
	}
	.post-container .slick-dots li.slick-active{
		background-color: black;
	}
    .summary span {
        font-size: 12px !important;
        color: grey !important;
        line-height:1.2 !important;
    }
    @media screen and (min-width: 768px){
        .hidden-mobile{
            display: block;
        }

        .post-container.slick-center-left .slick-list .slick-track {
            display: contents;
        }

        .post-detail .summary-post .summary{
            font-size: 14px;
            color: grey;
            display: -webkit-box;
            -webkit-box-orient: vertical;
            -webkit-line-clamp: 3;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: normal;
        }
        .post-item {
            position: relative;
            text-decoration: none;
            white-space: normal;
            overflow-wrap: break-word;
            height: 258px;
            margin-right: 16px;
            border: 1px solid #ccc;
            border-radius: 0.5rem;
        }
        .post-detail .date {
            font-size: 14px;
            color: grey;
            position: absolute;
            bottom: 0;
        }
        .post-detail .title {
            font-size: 14px; 
            font-weight: 600;
            color: black;
            display: -webkit-box;
            -webkit-box-orient: vertical;
            -webkit-line-clamp: 2;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: normal; 
        }
        .post-image-detail {
            border-top-right-radius: 0.5rem;
            border-top-left-radius: 0.5rem;
        }
    }
    @media (max-width: 767px) {
        .hidden-mobile{
            display: none;
        }
        .post-detail header h1 {
            font-size: 24px;
        }
        .content .news_if div span span span {
            font-size: 24px !important;
        }

        .post-container.slick-center-left .slick-list .slick-track {
            display: contents;
        }

        .post-detail .summary-post .summary{
            font-size: 12px;
            color: grey;
            display: -webkit-box;
            -webkit-box-orient: vertical;
            -webkit-line-clamp: 3;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: normal;
            font-weight: 500;
        }
        .post-item {
            position: relative;
            text-decoration: none;
            white-space: normal;
            overflow-wrap: break-word;
            min-height: 220px;
            margin-right: 10px;
            border: 1px solid #ccc;
            border-radius: 0.5rem;
        }
        .post-detail .date {
            font-size: 14px;
            color: grey;
            position: absolute;
            bottom: 0;
        }
        .post-detail .title {
            font-size: 14px; 
            font-weight: 600;
            color: black;
            display: -webkit-box;
            -webkit-box-orient: vertical;
            -webkit-line-clamp: 2;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: normal; 
        }
        .post-image-detail {
            max-height: 80px!important;
            border-top-right-radius: 0.5rem;
            border-top-left-radius: 0.5rem;
        }
    }
</style>
