<div class="ctm-form">
    <div id="firstAddress">
        <label class="form-group has-float-label">
            <input name="cfa_email" class="form-control" type="email" placeholder="email@abc.com"
                data-rule-required="true"
                data-rule-email="true"
                data-msg-required="Vui lòng nhập email"
                data-msg-email="Vui lòng nhập email đúng định dạng" />
            <span>Email</span>
        </label>

        <label class="form-group has-float-label">
            <input name="cfa_name" class="form-control" type="text" placeholder="Nhập họ và tên"
                data-rule-required="true"
                data-msg-required="Vui lòng nhập họ tên" />
            <span>Họ và tên</span>
        </label>

        <label class="form-group has-float-label">
            <input name="cfa_phone" id="cfa_phone" class="form-control" type="tel" placeholder="Nhập số điện thoại"
            data-rule-required="true"
            data-rule-digits="true"
            data-msg-required="Vui lòng nhập số điện thoại"
            data-msg-digits="Vui lòng nhập số điện thoại hợp lệ" />
            <span>Số điện thoại</span>
        </label>

        <label class="form-group has-float-label">
            <input name="cfa_address" class="form-control" type="text" placeholder="Nhập địa chỉ"
                data-rule-required="true"
                data-msg-required="Vui lòng nhập địa chỉ" />
            <span>Địa chỉ</span>
        </label>
        <label class="form-group has-float-label">
            <input name="cfa_place" class="form-control" type="text" placeholder="Nhập Tỉnh Hoặc Thành Phố"
                data-rule-required="true"
                data-msg-required="Vui lòng nhập tỉnh hoặc thành phố" />
            <span>Tỉnh/Thành Phố</span>
        </label>

    </div>
    <label class="form-group has-float-label">
        <textarea class="form-control" name="note" placeholder="Ghi chú thêm về thời gian giao hàng, địa chỉ,..."></textarea>
        <span>Ghi chú</span>
    </label>
    

    <button class="btn btn-block btn-primary btn-lg" type="submit">Đặt hàng</button>    
</div>
