<div class="ctm-cart">
    <div class="product-list">
		<div class="scroller">
	        <?php foreach ($this->cart_list as $key => $value) { ?>
	        <?php
            if(empty($value['id_combo'])==false){
                $photo = "";
	            if (empty($value["image_cb"]) == false) {
	                $photo = PHOTO_PATH . $value["image_cb"];
	            }
            }else {
                $photo = "";
	            if (empty($value["image"]) == false) {
	                $photo = PHOTO_PATH . $value["image"];
	            }
            }
	        ?>
	        <div class="product-item">
	            <?php echo $this->partial('/shared/_lazy_image.phtml', array(
	                'ratio' => '1x1',
	                'css' => 'photo',
	                'url' => $photo
	            )) ?>
	            <div class="qty"><?php echo $value['qty'] ?></div>
	            <div class="name"><?php echo $value['title'] ?><?php if(empty($value['variant_name']) == false){?></br>Màu: <?php echo isset($value['variant_name']) ?$value['variant_name'] :'Mặc Định' ?> <?php }?></div>
                <div class="price">
                    <?php 
                    $now = date('Y-m-d H:i:s');
                    if(($now < $value['count_time']) and($value['enable_promo']==1) ){
                        if (empty($value['variant_name'])) {
                            $price = $value['price_flash_sale'];
                        }else {
                            $price = ($value['variant_price_flash_sale']>0) ? $value['variant_price_flash_sale']:$value['variant_price_sales'];
                        }
                    
                    }else{
                        if (empty($value['variant_name'])) {
                            $price = $value['price_sales'];
                        } else {
                            $price = $value['variant_price_sales'];
                        }
                    }?>
                    <strong id="p_price" p_price="<?php echo $price ?>"><?php echo number_format($price) . '&#8363' ?></strong>
                </div>
	        </div>
	        <?php } ?>
        </div>
    </div>
    <div class="code-form">
        <span class="message-game hiddens" style="color:red">Nếu đơn hàng có máy game (* bắt buộc chọn Có máy game).</span>     
        <div class="check-cod" style="border-bottom: 1px solid #cbcbcb;margin-bottom: 1rem;">
            <div class="no-cod" role="tab">
                <label class="custom-control custom-radio" data-toggle="collapse">
                    <input type="radio" name="cod" value="1" id="no-cod" style="margin-right: 1rem" />
                    <span class="custom-control-desc">Không máy game</span>
                </label>
            </div>
            <div class="has-cod hiddens" role="tab">
                <label class="custom-control custom-radio" data-toggle="collapse" >
                    <input type="radio" name="cod" id="has-cod" value ="2" style="margin-right: 1rem" />
                    <span class="custom-control-description-check">Có máy game</span>
                    <span style="color:red" class="custom-control-descrip">&nbsp;(*)</span>
                </label>
            </div>
        </div>
        <input type="hidden" id ="checked-value" value = "<?php echo $this->checkedValue ?>">
        <div class="form-group">
            <label>Mã giảm giá</label>
            <input name="promotionCode" id="promotionCode" class="form-control" type="text" />
            <input type="hidden" id="checkPromotion" name="checkPromotion" value="false">
            <span class="loading_promotion" style="margin-left: .5rem; margin-top:.5rem;display: none; "><i class="fa fa-circle-o-notch fa-spin" style="font-size:18px"></i></span>
            <button id="btnPromotion" type="button" class="btn btn-primary">Áp dụng</button>
            <em class="form-message error error-promotion" style="display:none"></em>
        </div>
        <?php if(empty($this->customer) == false ){ ?>
            <div class="form-group">
                <label>Sử dụng điểm chiết khấu</label>
                <input name="discount" id="discount" class="form-control" type="text" />
                <input type="hidden" name="checkdisCount" id="checkdisCount" value="false">
                <span class="loading_discount" style="margin-left: .5rem; margin-top:.5rem;display: none; "><i class="fa fa-circle-o-notch fa-spin" style="font-size:18px"></i></span>
                <button id="btnDisCount" type="button" class="btn btn-primary">Áp dụng</button>
                <em class="form-message error error-discount" style="display:none"></em>
                <em class="form-message" style="font-style: italic;">Điểm hiện tại: <?php echo number_format($this->customer['score'])?></em>
            </div>
        <?php } ?>
    </div>
    <div class="subtotal-list">
        <div class="line">
            <label>Tạm tính:</label>
            <span class="price"><?php echo number_format($this->total) . '&#8363' ?></span>
        </div>
        <div class="line">
            <label>Giảm giá:</label>
            <span class="price text-success">- <?php echo '<span id="priceDiscount">'.number_format(0).'</span>' . '&#8363' ?></span>
        </div>
    </div>
    <div class="fee-shipping">
    <?php
        $sessionHelper = new My_Controller_Action_Helper_Session();
        $fee_ship = $sessionHelper->getSession('fee_ship');
    ?>
        <div class="line">
            <label>Phí vận chuyển:</label>
            <span class="price hidden" id="fee-ship">
                <?php
                if ($fee_ship !== null) {
                    echo number_format($fee_ship).'&#8363';
                } 
                ?>
            </span>
            <input type="hidden" id ="fee-ship-last" value = "0">
        </div>
    </div>

    <div class="fee-cod" style="display:block">
        <div class="line">
            <label>Phí COD:</label>
            <span class="price" id="fee-cod"></span>
            <input type="hidden" id ="fee-cod-last" value = "0">
        </div>
    </div>
    <div class="cart-total">
        <div class="line">
            <label>Tổng cộng</label>
            <input type="hidden" id ="currTotalPrice" value = "<?php echo $this->total ?>">
            <span class="price " id="totalPrice" data-total="<?php echo number_format($this->total)?>">
            <?php 
                echo  number_format($this->total). '&#8363';
             ?></span>
             
        </div>
    </div>
    <a href="/don-hang/gio-hang" class="btn-block">
        <i class="fa fa-angle-left"></i>
        <span>Quay lại giỏ hàng</span>
    </a>
</div>
<div id="popup">
    <h2 style = "color:black">Thông báo</h2>
    <p style = "color:red">Nếu đơn hàng có máy game (* bắt buộc chọn Có máy game).</p>
    <button id="closePopup">Đóng</button>
</div>

<style>
    .hidden {
            visibility: hidden;
    }
    .hiddens {
        display: none;
    }
    .fee-shipping,.fee-cod  {
        margin-bottom: 1rem;
        padding-bottom: 0.75rem;
        border-bottom: 1px solid #cbcbcb;
    }
    .fee-shipping .line .price, .fee-cod .line .price {
        float: right;
        font-weight: bold;
        font-size: 1.25rem;
        color: #dc2535;
    }

    #popup h2 {
        font-size: 1.5em;
        margin-bottom: 10px;
    }

    #popup {
        display: none;
        position: fixed;
        top: 20%;
        left: 50%;
        transform: translate(-50%, -50%);
        padding: 20px;
        background-color: #fff;
        border: 1px solid #ccc;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        z-index: 9999;
    }
    @media (max-width: 480px) {
        #popup {
            top:100px;
            width: 100%;
            left: 0;
            transform: translate(0, 0);
        }
    }

</style>
