<div id="payment" class="payment" role="tablist">
    <div class="card">
        <div class="card-header" role="tab">
            <label class="custom-control custom-radio" data-toggle="collapse" data-parent="#payment" data-target="#pm2">
                <input class="custom-control-input" type="radio" checked name="pm" value="2"/>
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description">Thanh toán khi giao hàng (COD)</span>
                <i class="fa fa-truck"></i>
            </label>
        </div>
        <div id="pm2" class="collapse show" role="tabpanel">
            <div class="card-block">
                Hero Game hỗ trợ ship hàng COD (giao máy thu tiền tận nơi)
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" role="tab">
            <label class="custom-control custom-radio" data-toggle="collapse" data-parent="#payment" data-target="#pm1">
                <input class="custom-control-input" type="radio" name="pm"  value="1" />
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description">Chuyển khoản qua ngân hàng</span>
                <i class="fa fa-credit-card"></i>
            </label>
        </div>
        <div id="pm1" class="collapse" role="tabpanel">
            <div class="card-block">
                <ul>
                    <li>
                        <strong class="title">Ngân hàng Vietcombank</strong><br/>
                        <label>Số tài khoản:</label><strong>037 1000 406 597</strong><br/>
                        <label>Chủ tài khoản:</label><strong>Giang Nhựt Hùng</strong><br/>
                        <label>Chi nhánh:</label><strong>Hồ Chí Minh</strong>
                    </li>
                    <li>
                        <strong class="title">Ngân hàng Agribank</strong><br/>
                        <label>Số tài khoản:</label><strong>1604 205 301 770</strong><br/>
                        <label>Chủ tài khoản:</label><strong>Giang Nhựt Hùng</strong>
                    </li>
                    <li>
                        <strong class="title">Ngân hàng Đông Á</strong><br/>
                        <label>Số tài khoản:</label><strong>010 892 5667</strong><br/>
                        <label>Chủ tài khoản:</label><strong>Lê Thị Ngọc Quyên</strong>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-header" role="tab">
            <label class="custom-control custom-radio" data-toggle="collapse" data-parent="#payment" data-target="#pm3">
                <input class="custom-control-input" type="radio" name="pm" value="3" />
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description">Trả tiền mặt và nhận hàng trực tiếp tại Hero Game</span>
                <i class="fa fa-money"></i>
            </label>
        </div>
        <div id="pm3" class="collapse" role="tabpanel">
            <div class="card-block">
                <p>Trụ sở chính: Hero Game</p>
                <p>Store HCM: Số 5 Nguyễn Trọng Tuyển, P.15, Phú Nhuận, HCM.</p>
                <p>Store HN: ⁣ Số 17 ngõ 7 Phùng Chí Kiên, Cầu Giấy, Hà Nội.</p>
                <p>Hotline: <a href="tel:+84906221218">090.622.1218</a></p>
            </div>
        </div>
    </div>
</div>
