<div class="page-header">
	<div class="page-header-content">
		<div class="page-title">
			<h4><i class="icon-cog3 position-left"></i> <span class="text-semibold">Tạo list price sales</span></h4>
		</div>
	</div>
	<div class="breadcrumb-line">
		<ul class="breadcrumb">
			<li><a href="/"><i class="icon-home2 position-left"></i> <?php echo $this->translate('home')?></a></li>
			<!-- <li><a href="/admin/combo-product">Danh Sách Combo Sản Phẩm</a></li>
			<li class="active">Chi tiết</li> -->
		</ul>
		<!-- tree -->
	</div>
</div>
<div class="content">
	<div class="panel panel-flat">
		<div class="panel-heading">
			<h5 class="panel-title">Chi Tiết</h5>
		</div>
		<div class="panel-body">
			<div class="alert alert-success alert-styled-left <?php if( empty($this->success) == true) { echo 'hidden';}?>">
				<button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
				<?php
					if( empty($this->success) == false ){
						foreach ($this->success as $key => $value ){
							echo $value.'<br/>';
						}
					}
				?>
			</div>
			<div class="alert alert-danger alert-styled-left <?php if( empty($this->error) == true) { echo 'hidden';}?>">
				<button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
				<?php
					if( empty($this->error) == false ){
						foreach ($this->error as $key => $value ){
							echo $value.'<br/>';
						}
					}
				?>
			</div>
			<div class="col-lg-12 form-flash-sale " id='form-flash-sale'>
				<form class="form-horizontal" id="the-flash-sale" method="post" enctype="multipart/form-data">
					<fieldset class="content-group">
						<div class="form-group">
							<button type="button" class="btn btn-primary add-product-sale"  data-flashSale-id="0" data-product-index="0" data-target="#modalProductList" style="margin-right: 11px;"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Thêm sản phẩm</button>
							<label class="control-label col-lg-2">Chọn sản phẩm</label>
							<div class="col-lg-8 list-product" id="listProduct_0" style="margin-left: -10px;">
								<div class="form-group file-item">
									<div class="col-lg-3">
										<!-- <input type="hidden" name="sale_id[]" value="0" /> -->
										<input type="text" class="form-control product-name-input" value="" placeholder="Chọn sản phẩm"  data-flash-sale-id="0" data-input-id="0" />
										<input type="hidden" class="form-control product-id-input" name="product_id[]" value="" placeholder=""  data-flash-sale-id="0" data-input-id="0" />
										<span class="errorSanPham" style="color:red"></span>
									</div>
									<div class="col-lg-2">
										<input type="tel" class="form-control product-price-input" name="price[]"  value="" placeholder="Giá sản phẩm "  data-flash-sale-id="0" data-input-id="0" oninput="this.value = this.value.replace(/[^0-9]/g, '');"/>
										<span class="errorPrice" style="color:red"></span>
									</div>
									<div class="col-lg-2">
										<input type="tel" class="form-control product-price-sale-input" name="price_sales[]"  value="" placeholder="Giá sale"  data-flash-sale-id="0" data-input-id="0" oninput="this.value = this.value.replace(/[^0-9]/g, '');"/>
										<span class="errorPrice" style="color:red"></span>
									</div>
									<div class="col-lg-1">
										<button type="button"  class="btn btn-alert remove-product" style="margin-right: 11px;">x</button>
									</div>
								</div>
							</div>
						</div>
					</fieldset>
					<div class="text-right">
						<input type="hidden" name="id" id="id" value="<?php echo @$this->id ?>" />
						<a href="/admin/flash-sale-product"><button type="button" class="btn btn-default cancel-btn"><?php echo $this->translate('cancel')?><i class="icon-arrow-right14 position-right"></i></button></a>
						<button type="submit" class="btn btn-primary submit-btn"><?php echo $this->translate('submit')?> <i class="fa fa-plus" aria-hidden="true"></i></button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>


<!-- Modal form -->
<div class="modal fade" id="modalProductList" tabindex="-1" role="dialog" aria-labelledby="modalProductListLabel" aria-hidden="true">
	<div class="modal-dialog" style="width: 70%;margin: 30px auto;">
		<div class="modal-content">
		<div class="modal-header">
			<h4 class="modal-title" id="myModalLabel">Modal title</h4>
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		</div>
		<div class="modal-body">
			<form id="selectProduct">
				<table id="listProductTable" class="table datatable-pagination">
					<thead>
						<tr>
							<th class="text-center">Action</th>
							<th width="5%"><?php echo $this->translate('id')?></th>
							<th>Tên Sản Phẩm</th>
							<th width="8%">Hình Ảnh</th>
							<th width="8%">Danh Mục</th>
							<th>Giá</th>
							<th>Giá sales</th>
							<th><?php echo $this->translate('status')?></th>
						</tr>
					</thead>
				</table>
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Huỷ</button>
					<button type="submit" class="btn btn-primary">Xác nhận</button>
			</form>
		</div>
		</div>
	</div>
</div>



