
<!-- Messenger Plugin chat Code -->
<div id="fb-root"></div>

<!-- Your Plugin chat code -->
<div id="fb-customer-chat" class="fb-customerchat">
</div>

<script>
  var chatbox = document.getElementById('fb-customer-chat');
  chatbox.setAttribute("page_id", "100111066262770");
  chatbox.setAttribute("attribution", "biz_inbox");
</script>

<!-- Your SDK code -->
<script>
  window.fbAsyncInit = function() {
	FB.init({
	  xfbml            : true,
	  version          : 'v17.0'
	});
  };

  (function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0];
	if (d.getElementById(id)) return;
	js = d.createElement(s); js.id = id;
	js.src = 'https://connect.facebook.net/vi_VN/sdk/xfbml.customerchat.js';
	fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>
<a class="chat-mobile" href="https://m.me/100111066262770" target="_blank">
	<img src="/site/img/fb_mess.png" alt="">
</a>
<!-- <i class="fa fa-commenting-o" aria-hidden="true"></i> -->
<style>
	@media screen and (min-width: 768px){
		.chat-mobile {
			display: none;
		}
	}
	@media screen and (max-width: 767px){
		#fb-root {
			display: none !important;
		}
		#fb-customer-chat{
			display: none !important;
		}
		.chat-mobile {
			position: fixed;
			bottom: 14px;
			right: 0px;
			z-index: 999999999999999;
			width: 60px;
			height: auto;
			overflow: hidden;
			font-size: 44px;
		}
		.chat-mobile img {
			width: 44px;
			height: 44px;
			border: none;
		}
	}
	
</style>


