
<div id="fb-root"></div>
<style>
#cfacebook {
	position: fixed;
	bottom: 0px;
	right: 10px;
	z-index: 999999999999999;
	width: 250px;
	height: auto;
	overflow: hidden;
}

#cfacebook .fchat {
	float: left;
	width: 100%;
	height: 270px;
	overflow: hidden;
	display: none;
	background-color: #fff;
}

#cfacebook .fchat .fb-page {
	margin-top: -130px;
	float: left;
}

#cfacebook a.chat_fb {
	float: left;
	padding: 0 5px;
	width: 250px;
	color: #fff;
	text-decoration: none;
	height: 40px;
	line-height: 40px;
	text-shadow: 0 1px 0 rgba(0, 0, 0, 0.1);
	background-repeat: repeat-x;
	background-size: auto;
	background-position: 0 0;
	background-color: #3a5795;
	border: 0;
	border-bottom: 1px solid #133783;
	z-index: 9999999;
	margin-right: 12px;
	font-size: 18px;
}

#cfacebook a.chat_fb:hover {
	color: yellow;
	text-decoration: none;
}
</style>
<script>(function(d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) return;
              js = d.createElement(s); js.id = id;
              js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.5";
              fjs.parentNode.insertBefore(js, fjs);
              }(document, 'script', 'facebook-jssdk'));
      </script>
<script>
        jQuery(document).ready(function () {
            jQuery(".chat_fb").click(function() {
            jQuery('.fchat').toggle('slow');
            });
        });
    </script>
<div id="cfacebook" class="hidden-md-down"><a href="javascript:;" class="chat_fb"
	onclick="return false;"><i class="fa fa-comment-o"></i> Herogame - hỗ trợ online</a>
<div class="fchat">
<div class="fb-page" data-tabs="messages"
	data-href="https://www.facebook.com/herogamestore" data-width="250"
	data-height="400" data-small-header="false"
	data-adapt-container-width="true" data-hide-cover="false"
	data-show-facepile="true" data-show-posts="false"></div>
</div>
</div>
