<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class="icon-dice position-left"></i> <span class="text-semibold">Danh Mục - Thông Tin Danh Mục</span></h4>
        </div>
    </div>
    <div class="breadcrumb-line">
        <ul class="breadcrumb">
            <li><a href="/admin"><i class="icon-home2 position-left"></i> <?php echo $this->translate('home') ?></a></li>
            <li><a href="/admin/group-category">Danh sách Danh mục</a></li>
            <li class="active">Thông Tin Danh Mục</li>
        </ul>
        <!-- tree -->
    </div>
</div>
<div class="content">
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">Thông Tin Danh Mục</h5>
        </div>
        <div class="panel-body">
            <div class="alert alert-danger alert-styled-left <?php
            if (empty($this->error) == true) {
                echo 'hidden';
            }
            ?>">
                <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
                <?php
                if (empty($this->error) == false) {
                    foreach ($this->error as $key => $value) {
                        echo $value . '<br/>';
                    }
                }
                ?>
            </div>
            <form class="form-horizontal" id="categoryDetailForm" method="post" enctype="multipart/form-data">
                <fieldset class="content-group">
                    <legend class="text-bold"></legend>
                    <div class="form-group">
                        <label class="control-label col-lg-2">Tên danh mục</label>
                        <div class="col-lg-10">
                            <input type="text" name="name" id="name" placeholder="Tên danh mục" class="form-control" value="<?php echo @$this->info['name'] ?>" data-msg="Vui lòng nhập tên">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-lg-2">Mô tả</label>
                        <div class="col-lg-10">
                            <textarea  name="description" id="description" placeholder="Mô tả" class="form-control" ><?php echo @$this->info['description'] ?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
				        <label class="control-label col-lg-2">Giới Thiệu</label>
				        <div class="col-lg-10">
				            <textarea name="summary" class="rich-editor" data-height="400px" id="summary"  rows="5"><?php echo @$this->info['summary'] ?></textarea>
				        </div>
				    </div>
                    <div class="form-group">
                        <label class="control-label col-lg-2">Hình ảnh Trên Menu</label>
                        <div class="col-lg-5">
                            <input type="file" class="file-styled form-control" name='icon_on_menu' id="icon_on_menu"/> 
                        </div>
                        <label class="control-label col-lg-2"></label>
                        <?php if (empty($this->info) == false && empty($this->info['icon_on_menu']) == false) { ?>
                            <div class="col-lg-5">
                                <div class="col-lg-2 col-sm-4 parent">
                                    <div class="thumbnail">
                                        <div class="thumb">
                                            <img class="img-media img-thumbnail-item" src="<?php echo '/upload/images' . $this->info['icon_on_menu']; ?>" alt="">
                                            <div class="caption-overflow">
                                                <span>
                                                    <a class="btn border-white text-white btn-flat btn-icon btn-rounded 
                                                       ml-5 container-image" href="<?php echo '/upload/images' . $this->info['icon_on_menu']; ?>" data-popup="lightbox">
                                                        <i class="icon-plus3"></i>
                                                    </a>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-lg-2">Hình ảnh</label>
                        <div class="col-lg-5">
                            <input type="file" class="file-styled form-control" name='image' id="image"/> 
                        </div>
                        <label class="control-label col-lg-2"></label>
                        <?php if (empty($this->info) == false && empty($this->info['image']) == false) { ?>
                            <div class="col-lg-5">
                                <div class="col-lg-2 col-sm-4 parent">
                                    <div class="thumbnail">
                                        <div class="thumb">
                                            <img class="img-media img-thumbnail-item" src="<?php echo '/upload/images' . $this->info['image']; ?>" alt="">
                                            <div class="caption-overflow">
                                                <span>
                                                    <a class="btn border-white text-white btn-flat btn-icon btn-rounded 
                                                       ml-5 container-image" href="<?php echo '/upload/images' . $this->info['image']; ?>" data-popup="lightbox">
                                                        <i class="icon-plus3"></i>
                                                    </a>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-lg-2">Icon</label>
                        <div class="col-lg-5">
                            <input type="file" class="file-styled form-control" name='icon' id="icon"/> 
                        </div>
                        <label class="control-label col-lg-2"></label>
                        <?php if (empty($this->info) == false && empty($this->info['icon']) == false) { ?>
                            <div class="col-lg-5">
                                <div class="col-lg-2 col-sm-4 parent">
                                    <div class="thumbnail">
                                        <div class="thumb">
                                            <img class="img-media img-thumbnail-item" src="<?php echo '/upload/images' . $this->info['icon']; ?>" alt="">
                                            <div class="caption-overflow">
                                                <span>
                                                    <a class="btn border-white text-white btn-flat btn-icon btn-rounded 
                                                       ml-5 container-image" href="<?php echo '/upload/images' . $this->info['icon']; ?>" data-popup="lightbox">
                                                        <i class="icon-plus3"></i>
                                                    </a>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-lg-2">Icon Hover</label>
                        <div class="col-lg-5">
                            <input type="file" class="file-styled form-control" name='icon_hover' id="icon"/> 
                        </div>
                        <label class="control-label col-lg-2"></label>
                        <?php if (empty($this->info) == false && empty($this->info['icon_hover']) == false) { ?>
                            <div class="col-lg-5">
                                <div class="col-lg-2 col-sm-4 parent">
                                    <div class="thumbnail">
                                        <div class="thumb">
                                            <img class="img-media img-thumbnail-item" src="<?php echo '/upload/images' . $this->info['icon_hover']; ?>" alt="">
                                            <div class="caption-overflow">
                                                <span>
                                                    <a class="btn border-white text-white btn-flat btn-icon btn-rounded 
                                                       ml-5 container-image" href="<?php echo '/upload/images' . $this->info['icon_hover']; ?>" data-popup="lightbox">
                                                        <i class="icon-plus3"></i>
                                                    </a>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-lg-2">Url</label>
                        <div class="col-lg-10">
                            <input type="text" name="url_slug" id="url_slug" placeholder="Url" class="form-control" value="<?php echo @$this->info['url_slug'] ?>" data-msg="Vui lòng nhập đường dẫn">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-lg-2">Menu</label>
                        <div class="col-lg-2">
                            <select name="url_menu" id="url_menu" class="form-control">
                                <option value>Không Có</option>
                                <?php
                                if (empty($this->listMenu) == false) {
                                    foreach ($this->listMenu as $key => $value) {
                                        ?>
                                        <option value="<?php echo $value['url'] ?>" <?php
                                        if ($this->info['url_menu'] == $value['url']) {
                                            echo 'selected';
                                        }
                                        ?>>
                                            <?php echo $value['name'] ?></option>
                                        <?php
                                    }
                                }
                                ?>
                            </select>
                        </div>

                        <label class="control-label col-lg-1">Loai</label>
                        <div class="col-lg-2">
                            <select name="type_of_category" id="type_of_category" class="form-control">
                                <option value>Không Có</option>
                                <?php
                                if (empty($this->typeOfCategory) == false) {
                                    foreach ($this->typeOfCategory as $key => $value) {
                                        ?>
                                        <option value="<?php echo $key ?>" <?php
                                        if ($this->info['type_of_category'] == $key) {
                                            echo 'selected';
                                        }
                                        ?>>
                                            <?php echo $value ?></option>
                                        <?php
                                    }
                                }
                                ?>
                            </select>
                        </div>
                        
                        <label class="control-label col-lg-1"><?php echo $this->translate('status') ?></label>
                        <div class="col-lg-2">
                            <select name="status" id="status" class="form-control">
                                <option value="<?php echo STATUS_IN_ACTIVE ?>" <?php
                                if (@$this->info['status'] == STATUS_IN_ACTIVE) {
                                    echo 'selected';
                                }
                                ?>><?php echo $this->translate('in-active') ?></option>
                                <option value="<?php echo STATUS_ACTIVE ?>" <?php
                                if (@$this->info['status'] == STATUS_ACTIVE) {
                                    echo 'selected';
                                }
                                ?>><?php echo $this->translate('active') ?></option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-lg-2">&nbsp;</label>
                        <div class="col-lg-2">
                            <div class="checkbox">
                                <label>
                                    <div class="border-primary-600 text-primary-800"><span class="checked">
                                            <input type="checkbox" class="control-primary" name="show_in_menu" 
                                                <?php echo ( empty($this->info['show_in_menu']) == false ) ? 'checked="checked"' :"" ?> value="1"></span>
                                    </div>
                                    Show in Menu
                                </label>
                            </div>
                        </div>
                        <label class="control-label col-lg-1">&nbsp;</label>
                        <div class="col-lg-2">
                            <div class="checkbox">
                                <label>
                                    <div class="border-primary-600 text-primary-800"><span class="checked">
                                            <input type="checkbox" class="control-primary" name="show_in_home_cate_page" 
                                                <?php echo ( empty($this->info['show_in_home_cate_page']) == false ) ? 'checked="checked"' :"" ?> value="1"></span>
                                    </div>
                                    Hiển thị trên list danh mục trang chủ
                                </label>
                            </div>
                        </div>
                        <label class="control-label col-lg-2">&nbsp;</label>
                        <div class="col-lg-3">
                            <div class="checkbox">
                                <label>
                                    <div class="border-primary-600 text-primary-800"><span class="checked">
                                            <input type="checkbox" class="control-primary" name="show_list_product_home_page" 
                                                <?php echo ( empty($this->info['show_list_product_home_page']) == false ) ? 'checked="checked"' :"" ?> value="1"></span>
                                    </div>
                                    Hiển thị DS sản phẩm của danh mục này ở trang chủ
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-lg-2">Danh mục cha</label>
                        <div class="col-lg-2">
                            <select name="parent_category" id="parent_category" class="form-control">
                                <option value="0" data-level="-1">Top Level</option>
                                <?php
                                if (empty($this->parentCategoryList) == false) {
                                    foreach ($this->parentCategoryList as $key => $value) { ?>
                                        <option value="<?php echo $value["id"] ?>" 
                                                data-level="<?php echo $value["level_category"] ?>" 
                                        <?php
                                            if ($this->info['parent_category'] == $value["id"]) {
                                                echo 'selected';
                                            } ?>>
                                            <?php echo $value["name"] ?></option>
                                        <?php
                                    }
                                }
                                ?>
                            </select>
                        </div>
                        <!-- level -->
                        <label class="control-label col-lg-1"><?php echo $this->translate('level') ?></label>
                        <div class="col-lg-2">
                            <input type="number" name="level_category_display" id="level_category_display" disabled
                                   placeholder="<?php echo $this->translate('level_category') ?>" class="form-control" 
                                   value="<?php echo (isset($this->info['level_category']) == true ) ? $this->info['level_category']: 0 ?>">
                            <input type="hidden" name="level_category" id="level_category" value="<?php echo (isset($this->info['level_category']) == true ) ? $this->info['level_category']: 0 ?>" />
                        </div>
                        
                        <label class="control-label col-lg-1"><?php echo $this->translate('priority') ?></label>
                        <div class="col-lg-2">
                            <input type="number" name="priority" id="priority" placeholder="<?php echo $this->translate('priority') ?>" class="form-control" value="<?php echo @$this->info['priority'] ?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-lg-2">Mô tả thẻ meta</label>
                        <div class="col-lg-10">
                            <input maxlength="100" type="text" name="meta_description" id="meta_description" placeholder="Mô tả thẻ meta" class="form-control" value="<?php echo @$this->info['meta_description'] ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-lg-2">Tiêu đề trang</label>
                        <div class="col-lg-10">
                            <input type="text" name="title_page" id="title_page" placeholder="Tiêu đề trang" class="form-control" value="<?php echo @$this->info['title_page'] ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-lg-2">Keyword</label>
                        <div class="col-lg-10">
                            <input maxlength="100" type="text" name="keyword" id="keyword" placeholder="Keyword" class="form-control" value="<?php echo @$this->info['keyword'] ?>">
                        </div>
                    </div>
                </fieldset>
                <div class="text-right">
                    <a href="/admin/category"><button type="button" class="btn btn-default cancel-btn"><?php echo $this->translate('cancel') ?><i class="icon-arrow-right14 position-right"></i></button></a>
                    <button type="submit" class="btn btn-primary submit-btn"><?php echo $this->translate('submit') ?> <i class="fa fa-plus" aria-hidden="true"></i></button>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="modal_media" class="modal fade" data-keyboard="false" data-backdrop="static">
</div>