<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class="icon-dice position-left"></i> <span class="text-semibold">Danh Mục - Danh Sách Danh Mục</span></h4>
        </div>
        <div class="heading-elements">
            <a href="/admin/<?php echo $this->controller ?>/detail" class="btn btn-labeled btn-labeled-right bg-blue heading-btn"><?php echo $this->translate('create-category') ?> <b><i class="fa fa-plus" aria-hidden="true"></i></b></a>
        </div>
    </div>
    <div class="breadcrumb-line">
        <ul class="breadcrumb">
            <li><a href="/admin/index/"><i class="icon-home2 position-left"></i> <?php echo $this->translate('home') ?></a></li>
            <li><a href="/admin/category"><?php echo $this->translate('category') ?></a></li>
            <li class="active">Danh Sách Danh Mục</li>
        </ul>
        <!-- tree -->
    </div>
</div>
<div class="content">
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">Danh Sách Danh Mục</h5>
        </div>
        <div class="panel-body">
        </div>
        <table id="categoryTable" class="table datatable-pagination">
            <thead>
                <tr>
                    <th width="5%"><?php echo $this->translate('id') ?></th>
                    <th>Tên Danh Mục</th>
                    <th>Đường Dẫn</th>
                    <th>Ảnh</th>
                    <th>Menu</th>
                    <th><?php echo $this->translate('status') ?></th>
                    <th class="text-center"><?php echo $this->translate('action') ?></th>
                </tr>
            </thead>
        </table>
    </div>
</div>