<?php $this->viewCssClass = 'product index list' ?>
<div class="container">
    <div class="search-result" style="font-size: 1.1rem; height: 2.7rem;line-height: 2.7rem; padding: 0 0.75rem; font-weight: bold; border-top-left-radius: inherit;border-top-right-radius: inherit;margin-top:2rem; text-align: center;color: blue;">
        <?php if(empty($this->key)==false){
            echo '<i class="fa fa-search"></i> KẾT QUẢ TÌM KIẾM: '.$this->key .' '.count($this->productBySearch) .' items';
        } ?>
    </div>
    <div class="row">
        <aside class="col-md-2 no-gutter">
            <?php echo $this->render("/shared/_left-aside.phtml") ?>
        </aside>
        <section class="col-md-10 col-12 left-gutter">
                <?php if (empty($this->productBySearch) == false) {?>
                    <?php
                        echo $this->partial('/shared/_data_filter.phtml', array(
                            'sort' => $this->sortList,
                            'limit' => $this->pageSize,
                            'selected_page_size' => $this->selected_page_size,
                            'sorted' => $this->sorted
                        ))
                    ?>
                    <?php
                        $res = Commons::_buildProductResponse($this->paginator);
                        echo $this->partial('/shared/_product_view.phtml', array(
                            'data' => $res,
                            'dcol' => 4
                        ))
                    ?>
                    <!-- pagination -->
                    <?php if (count($this->paginator) > 1) { ?>
                    <?php echo $this->paginator; ?>
                <?php } ?>
                <?php }else { ?>
                    <div style="font-size: 1.1rem; height: 2.7rem;line-height: 2.7rem; padding: 0 0.75rem; font-weight: bold; border-top-left-radius: inherit;border-top-right-radius: inherit;margin-top:1rem; background: #2d97f1;color: white;">THÔNG BÁO</div>
                    <div style="font-size: xx-large; display: flex; justify-content: center; margin-top:5%; height: 100vh;">
                        <div style="text-align: center;">
                            Không tìm thấy sản phẩm. Mời bạn nhập vào từ khóa khác.
                        </div>
                    </div>

                <?php } ?>
        </section>
    </div>
</div>
<?php echo $this->render("/shared/_filter_submit_frm.phtml") ?>

