<div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalstatus">Cập nhật sản phẩm</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      		<div class="col-md-12 ">
				<div class="form-group">
					<label>
					<?php if( $this->type == 1){ 
							echo "Tên Sản Phẩm";
						} elseif ( $this->type == 2){ 
							echo "Giá Sản Phẩm";
						} else { 
							echo "Giá Khuyến Mãi"; 
						} ?>
						</label>
						<?php if( $this->type == 1){ 
							echo '<input type="text" class="form-control" id="nameP" value="'. $this->info['title'] .'">';
						} elseif ( $this->type == 2){ 
							echo '<input type="number" class="form-control" id="priceP" value="'. $this->info['price'] .'">';
						} else { 
							echo '<input type="text" class="form-control" id="salePS" value="'. $this->info['price_sales'] .'">';
						} ?>
				</div>
			</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
        <button type="button" class="btn btn-primary" id="saveproduct" data-id="" data-user="">Lưu</button>
        <input type="hidden" id="idProduct" value="<?php echo $this->idProduct ?>" />
        <input type="hidden" id="typeProduct" value="<?php echo $this->type ?>" />
      </div>
    </div>
  </div>