<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class="icon-stack3 position-left"></i> <span class="text-semibold">Sản Phẩm - Thông Tin Sản Phẩm</span></h4>
        </div>
    </div>
    <div class="breadcrumb-line">
        <ul class="breadcrumb">
            <li><a href="/admin/index"><i class="icon-home2 position-left"></i> <?php echo $this->translate('home') ?></a></li>
            <li><a href="/admin/product">Danh Sách Sản Phẩm</a></li>
            <li class="active">Thông Tin Sản Phẩm</li>
        </ul>
        <!-- tree -->
    </div>
</div>
<div class="content">
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">Thông Tin Sản Phẩm</h5>
        </div>
        <div class="panel-body">
            <div class="alert alert-danger alert-styled-left <?php
            if (empty($this->error) == true) {
                echo 'hidden';
            }
            ?>">
                <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
                <?php
                if (empty($this->error) == false) {
                    foreach ($this->error as $key => $value) {
                        echo $value;
                    }
                }
                ?>
            </div>
            <form class="form-horizontal" id="postDetailForm" method="post" enctype="multipart/form-data">
                <div class="col-md-12">
                    <div class="panel-body">
                                                <?php echo $this->partial("/product/_info.phtml", array('info' => @$this->info, 'listImg' => $this->listImg, 'listCategory' => $this->listCategory, 'listColor' => $this->listColor,'variants'=>$this->variants,'listVariantImg'=>$this->listVariantImg,'listCombo'=>$this->listCombo)); ?>

                    </div>
                </div>
                <div class="text-right">
                    <a href="/admin/product"><button type="button" class="btn btn-default cancel-btn"><?php echo $this->translate('cancel') ?><i class="icon-arrow-right14 position-right"></i></button></a>
                    <button type="submit" class="btn btn-primary submit-btn"><?php echo $this->translate('submit') ?> <i class="fa fa-plus" aria-hidden="true"></i></button>
                </div>
            </form>
        </div>
    </div>
</div>
<div id="modal_media" class="modal fade" data-keyboard="false" data-backdrop="static">
</div>