<table border="0" cellpadding="0" cellspacing="0" width="100%"
	height="100%"
	style="border-spacing: 0; border-collapse: collapse; font-size: 14px">
	<tbody>
		<tr>
			<td align="center" valign="top" style="border-collapse: collapse">

				<table width="600" border="0"
					cellpadding="0" cellspacing="0"
					style="border-spacing: 0; border-collapse: collapse; font-size: 14px; max-width: 600px">
					<tbody>
						<tr>
							<td
								style="border-collapse: collapse">
								<table width="100%" border="0" cellpadding="0" cellspacing="0"
									style="border-spacing: 0; border-collapse: collapse; font-size: 14px; border-bottom: 1px solid #dee2e3; width: 100% !important">
									<tbody>
										<tr>
											<td width="50%" height="49" valign="middle"
												style="border-collapse: collapse; width: 50%"><a
												href="herogame.vn" target="_blank"><img
													src="http://<?php echo $_SERVER['SERVER_NAME']?>/site/img/logo.png"
													width="100"></a></td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>

						<tr>
							<td style="border-collapse: collapse">

								<table border="0"
									cellpadding="0" cellspacing="0" align="left"
									style="border-spacing: 0; border-collapse: collapse; font-size: 14px">
									<tbody>
										<tr>
											<td valign="top" style="border-collapse: collapse">
												<div
													style="margin-top: 20px">
													<strong 
														style="font-size: 16px">
														Kính chào quý khách <?php echo $this->orderInfo['name']?>,
													</strong>
												</div>
												<div style="margin-top: 10px; margin-bottom: 20px">
													Cảm ơn bạn đã đặt hàng tại Herogame.
													<strong style="color: #f36f21">Đơn hàng # <?php echo $this->orderInfo['order_code']?></strong> của
													quý khách đặt ngày <strong><?php echo date("d/m/Y", strtotime($this->orderInfo['created_date'])); ?></strong>
													với hình thức thanh toán là <strong><?php 
														if( $this->orderInfo['payment_method'] == 1 ) { 
															echo 'Chuyển khoản';
														} else if( $this->orderInfo['payment_method'] == 2 ){
															echo 'COD';
														} else if( $this->orderInfo['payment_method'] == 3 ){
															echo 'Trả tiền mặt tại shop';
														}
													?></strong>.
												</div>
												<div style="margin-top: 10px; margin-bottom: 20px">
												    Herogame xin thông báo đơn hàng của bạn đã bị hủy.<br>
												    Lý do: <strong><?php echo $this->orderInfo['reject_reason']?></strong>
											    </div>
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
	</tbody>
</table>