<div class="page-header">
	<div class="page-header-content">
		<div class="page-title">
			<h4>
				<i class="icon-cart-add2 position-left"></i> <span
					class="text-semibold">Đơn Hàng - Thông Tin Đơn Hàng</span>
			</h4>
		</div>
	</div>
	<div class="breadcrumb-line">
		<ul class="breadcrumb">
			<li><a href="/"><i class="icon-home2 position-left"></i> Trang chủ</a></li>
			<li><a href="/admin/order">Danh Sách Đơn Hàng</a></li>
			<li class="active">Thông Tin Đơn Hàng</li>
		</ul>
		<!-- tree -->
	</div>
</div>
<div class="content">
	<div class="panel panel-flat">
		<div class="panel-heading">
			<h5 class="panel-title">Thông Tin Đơn Hàng</h5>
		</div>
		<div class="panel-body">
			<div
				class="alert alert-danger alert-styled-left <?php
				if (empty ( $this->error ) == true) {
					echo 'hidden';
				}
				?>">
				<button type="button" class="close" data-dismiss="alert">
					<span>×</span><span class="sr-only">Đóng</span>
				</button>
                <?php
					if (empty ( $this->error ) == false) {
						foreach ( $this->error as $key => $value ) {
							echo $value . '<br/>';
						}
					}
				?>
            </div>
			<form class="form-horizontal" id="orderForm" method="post"
				enctype="multipart/form-data">
				<fieldset class="content-group">
					<legend class="text-bold"></legend>
					<div class="form-group">
						<label class="control-label col-lg-2">Tên Người Mua</label>
						<div class="col-lg-2">
							<input type="text" name="name" id="name"
								placeholder="Tên Người Mua" class="form-control"
								value="<?php echo @$this->info['name'] ?>"
								data-msg="Vui lòng nhập tên">
						</div>
						<label class="control-label col-lg-1">User</label>
						<div class="col-lg-7">
							<select name="userId" id="userId" class="form-control" <?php if( empty($this->info['user_id']) == false ){ echo 'disabled="disabled"';}?>>
								<?php if( empty($this->info['user_name']) == false ){?>
									<option value="<?php echo $this->info['user_id'];?>" selected="selected"><?php echo $this->info['user_name']?></option>
								<?php } else { ?>
									<option value="-1" selected="selected">Khách Mới</option>
								<?php } ?>
							</select>
							<input type="hidden" name="hiddenId" id="hiddenId" data-user="<?php echo $this->info['user_name']?>" value="<?php echo $this->info['user_id'];?>">
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-lg-2">Mã khuyến mãi</label>
						<div class="col-lg-2">
							<input type="text" name="code" id="code" <?php if( @$this->id > 0 ){ echo 'disabled="disabled"';}?>
								placeholder="Mã khuyến mãi" class="form-control"
								value="<?php echo @$this->info['promotion_code'] ?>"
								data-msg="Vui lòng nhập mã khuyến mãi">
						</div>
						<?php if(empty($this->id) == true ){?>
						<button type="button" class="btn btn-success addpromotion">
							Áp Dụng <i class="fa fa-gift" aria-hidden="true"></i>
						</button>
						<?php } ?>
						<input type="hidden" id="apdungma" data-percent="" data-max="" name="apdungma" value="false">
					</div>
					<?php if(empty($this->info['user_id']) == false && $this->info['user_id'] != -1 ){?>
						<div class="form-group">
							<label class="control-label col-lg-2">Điểm Cộng</label>
							<div class="col-lg-2">
								<input type="text" name="score" id="score" disabled="disabled"
									placeholder="" class="form-control"
									value="<?php echo $this->info['score'] ?>">
							</div>
							<label class="control-label col-lg-1">Giảm giá</label>
							<div class="col-lg-2">
								<input type="text" name="discount" id="discount" disabled="disabled"
									placeholder="" class="form-control"
									value="<?php echo $this->info['discount'] ?>">
							</div>
						</div>
					<?php } ?>
					<div class="form-group">
						<label class="control-label col-lg-2">Địa Chỉ</label>
						<div class="col-lg-10">
								<textarea rows="3" placeholder="Địa Chỉ" name="address" id="address" class="form-control" data-msg="Vui lòng nhập địa chỉ"><?php echo @$this->info['address'] ?></textarea>
						</div>
					</div>
					<?php
					if(empty($this->info['place']) == false){?>
						<div class="form-group">
							<label class="control-label col-lg-2">Tỉnh/Thành Phố</label>
							<div class="col-lg-10">
									<textarea rows="3" placeholder="Địa Chỉ" name="place" id="place" class="form-control" data-msg="Vui lòng nhập tỉnh/thành phố"><?php echo @$this->info['place'] ?></textarea>
							</div>
						</div>
				    <?php }?>

					<?php
						if(empty($this->info['ma_province']) == false){?>
							<div class="form-group">
							<label class="control-label col-lg-2">Tỉnh thành phố </label>
							<div class="col-lg-10">
								<select name="province" id="province" class="form-control choose province" disabled >
									<option value=''>Chọn tỉnh thành phố</option>
									<?php
									if (empty($this->listProvince) == false) {
										foreach ($this->listProvince as $key => $value) {
									?>
											<option  
												<?php
												if ($value['matp'] == @$this->info['ma_province']) {
												echo 'selected';
												}?>
												value="<?php echo $value['matp'] ?>"
												>
												<?php echo $value['name_province'] ?>
											</option>
										<?php
										}
									} 
									?>
								</select>
								<span id="provinceError" style="color: red;"></span>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-lg-2"> </label>
							<div class="col-lg-10">
								<select name="district" id="district" class="form-control choose district" disabled >
									<option value=''>Chọn quận huyện</option>
									<?php
									if (empty($this->listDistrict) == false) {
										foreach ($this->listDistrict as $key => $value) {
									?>
											<option  
												<?php
												if ($value['maqh'] == @$this->info['ma_district']) {
												echo 'selected';
												}?>
												value="<?php echo $value['maqh'] ?>"
												>
												<?php echo $value['name_district'] ?>
											</option>
										<?php
										}
									} 
									?>
								</select>
								<span id="districtError" style="color: red;"></span>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-lg-2"> </label>
							<div class="col-lg-10">
								<select name="wards" id="wards" class="form-control choose wards" disabled>
									<option value=''>Chọn phường xã</option>
									<?php
									if (empty($this->listWards) == false) {
										foreach ($this->listWards as $key => $value) {
									?>
											<option  
												<?php
												if ($value['xaid'] == @$this->info['ma_wards']) {
												echo 'selected';
												}?>
												value="<?php echo $value['xaid'] ?>"
												>
												<?php echo $value['name_wards'] ?>
											</option>
										<?php
										}
									} 
									?>
								</select>
								<span id="wardsError" style="color: red;"></span>
							</div>
						</div>
				    <?php }?>
					<div class="form-group">
						<label class="control-label col-lg-2">Điện Thoại</label>
						<div class="col-lg-10">
							<input type="text" name="phone" id="phone"
								placeholder="Điện thoại" class="form-control"
								value="<?php echo @$this->info['phone'] ?>"
								data-msg="Vui lòng nhập điện thoại">
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-lg-2">Email</label>
						<div class="col-lg-10">
							<input type="text" name="email" id="email"
								placeholder="Email" class="form-control"
								value="<?php echo @$this->info['email'] ?>">
						</div>
					</div>
					
					<div class="form-group">
						<label class="control-label col-lg-2">Trạng Thái</label>
						<div class="col-lg-4">
							<select name="status" id="status" class="form-control">
								<?php
									foreach ( Commons::getStatusOrder() as $key => $value ){
										?>
										<option value="<?php echo $key?>" <?php if( $key == @$this->info['status']) { echo 'selected'; }?>><?php echo $value?></option>
										<?php
									}
								?>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-lg-2">Thanh Toán</label>
						<div class="col-lg-4">
							<select name="is_pay" id="is_pay" class="form-control">
								<option value="0" <?php if( @$this->info['is_pay'] == 0 ){ echo 'selected'; }?>>Chưa Thanh Toán</option>
								<option value="1" <?php if( @$this->info['is_pay'] == 1 ){ echo 'selected'; }?>>Đã Thanh Toán</option>
							</select>
						</div>
					</div>
                    <div class="form-group">
						<label class="control-label col-lg-2">Phương Thức Thanh Toán</label>
						<div class="col-lg-4">
							<select name="payment_method" id="payment_method" class="form-control">
								<option value="1" <?php if( @$this->info['payment_method'] == 1 ){ echo 'selected'; }?>>Chuyển Khoản</option>
								<option value="2" <?php if( @$this->info['payment_method'] == 2 ){ echo 'selected'; }?>>COD</option>
                                                                <option value="3" <?php if( @$this->info['payment_method'] == 3 ){ echo 'selected'; }?>>Trả Tiền Mặt Tại Shop</option>
							</select>
						</div>
					</div>
					<?php
						if(empty($this->info['cod']) == false){?>
						<div class="form-group">
							<label class="control-label col-lg-2">Check COD</label>
							<div class="col-lg-4">
								<select name="cod" id="cod" class="form-control" disabled >
									<option value="1" <?php if( @$this->info['cod'] == 1 ){ echo 'selected'; }?>>Không có máy game</option>
									<option value="2" <?php if( @$this->info['cod'] == 2 ){ echo 'selected'; }?>>Có máy game</option>
								</select>
							</div>
						</div>
					<?php }?>
					
                    <div class="form-group">
						<label class="control-label col-lg-2">Ghi Chú</label>
						<div class="col-lg-10">
                                                    <textarea rows="3" placeholder="Ghi Chú" name="note" id="note" class="form-control"><?php echo @$this->info['note'] ?></textarea>
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-lg-2">Giảm Giá</label>
						<div class="col-lg-10">
							<input type="number" name="admin_discount" id="admin_discount" placeholder="Vui Lòng Nhập Số Tiền Muốn Giảm" class="form-control" value="<?php echo @$this->info['admin_discount'] ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-lg-2">Lý Do:</label>
						<div class="col-lg-10">
                            <textarea rows="3" placeholder="Lý Do Hủy Đơn Hàng Hay Giảm Giá" name="reject_reason" id="reject_reason" class="form-control"><?php echo @$this->info['reject_reason'] ?></textarea>
						</div>
					</div>
					<div class="form-group2" style ="display: flex;
													justify-content: space-between;
													align-items: center;
													margin-right: 20px;
													margin-left: -10px;">
						<label class="control-label col-lg-1">Tạm tính</label>
						<div class="col-2">
							<span style="color: red; font-size: 20px" id="total_show"><?php if( empty($this->id) == false ){ 
								echo number_format($this->info['total_before_sale']);} else { echo '0';}?></span> VNĐ
							<input type="hidden" name="total" id="total_hide" value="0">
						</div>
						<label class="control-label col-lg-1">Phí vận chuyển</label>
						<div class="col-2">
							<span style="color: red; font-size: 20px" id="total_show"><?php if( empty($this->id) == false ){ 
								echo number_format(+ $this->info['fee_ship']);} else { echo '0';}?></span> VNĐ
							<input type="hidden" name="fee_ship" id="fee_ship_hide" value="0">
						</div>
						<?php if(empty($this->info['cod'])==false){?>	
							<label class="control-label col-lg-1">Phí COD</label>
							<div class="col-2">
								<span style="color: red; font-size: 20px" id="total_show"><?php if( empty($this->id) == false ){ 
									echo number_format(+ $this->info['fee_cod']);} else { echo '0';}?></span> VNĐ
								<input type="hidden" name="fee_ship" id="fee_ship_hide" value="0">
							</div>
						<?php } ?>

						<?php if(empty($this->info['promotion_price'])==false){?>	
							<label class="control-label col-lg-1">Khuyến mãi</label>
							<div class="col-2">
								<span style="color: red; font-size: 20px" id="total_show"><?php if( empty($this->id) == false ){ 
									echo number_format(- $this->info['promotion_price']);} else { echo '0';}?></span> VNĐ
								<input type="hidden" name="promotion_price" id="promotion_price_hide" value="0">
							</div>
						<?php } else {?>
							<label class="control-label col-lg-1">Khuyến mãi</label>
							<div class="col-2">
								<span style="color: red; font-size: 20px" id="total_show"><?php if( empty($this->id) == false ){ 
									echo number_format(- $this->info['discount']);} else { echo '0';}?></span> VNĐ
								<input type="hidden" name="discount" id="discount" value="0">
							</div>
						<?php } ?>
						
						<label class="control-label col-lg-1">Thành tiền</label>
						<div class="col-2">
							<?php 
								$total = 0;
                                    if( empty($this->info['total']) == false ){
                                        $total = $this->info['total'];
                                    }
                                         $not_discount = $total;
								if( empty($this->info['admin_discount']) == false ){
									$total = $total - $this->info['admin_discount'];
								}
								
							?>
							<span style="color: green; font-size: 20px" id="total_show_down"><?php if( empty($this->id) == false ){ echo number_format($total);} else { echo '0';}?></span> VNĐ
							<input type="hidden" name="total_down" id="total_hide_down" value="<?php echo $not_discount?>">
						</div>
					</div>
					<?php if( empty($this->id) == true ){ ?>
					<div class="form-group">
						<label class="control-label col-lg-2">Chọn Sản Phẩm</label>
						<div class="col-lg-5">
							<select name="product" id="product" class="form-control">
							</select>
						</div>
						<div class="col-lg-2">
							<select  id="product_color" class="form-control">
								<?php
    								if( empty($this->color) == false){
    								    foreach ( $this->color as $key => $item){
    								        echo '<option value="'.$item['id'].'">'.$item['color_name'].'</option>';
    								    }
    								} else {
    								    ?>
    								    <option value="1">Màu Mặc Định</option>
    								    <?php
    								}
								?>
							</select>
						</div>
						<div class="col-lg-2">
							<input type="number" name="sluong" id="sluong"
								placeholder="Số Lượng" class="form-control"
								value="1">
						</div>
						<button type="button" class="btn btn-success addproduct">
							Thêm <i class="fa fa-cart-plus" aria-hidden="true"></i>
						</button>
					</div>
					<?php } ?>
					<div class="form-group">
						<label class="control-label col-lg-2">Danh Sách Sản Phẩm</label>
						<div class="col-lg-10">
							 <table id="listProduct" class="table datatable-sorting">
							 	<thead>
					                <tr>
										<th width="50px">#</th>
					                	<th width="150px">Ảnh</th>
					                    <th>Tên sản phẩm</th>
					                    <th width="10%">Màu</th>
					                    <th>Giá</th>
					                    <!-- <th>Giá Sell</th> -->
					                    <th>Số lượng</th>
					                    <?php if( empty($this->id) == true ){ ?>
					                    	<th>Hành động</th>
					                    <?php } ?>
					                </tr>
					            </thead>
					            <tbody id="listproductbody">
					            	<?php if( empty($this->info['order_detail']) == false ){
					            		foreach ( $this->info['order_detail'] as $key => $value ){
					            			?>
					            			<tr>
												<td><?php echo $key + 1?></td>
					            			<?php if( empty($value['combo_id']) == false ){?>
												<td><img width="40px" height="40px" src="/upload/images/<?php echo $value['c_img']?>" /></td>
					            			<?php } else {?>
												<td><img width="40px" height="40px" src="/upload/images/<?php echo $value['p_img']?>" /></td>

					            			<?php }?>
					            
					            				<td>
					            					<?php
					            					if( empty($value['c_combo_name']) == false ){
					            					  echo $value['c_combo_name'];
					            					} else {
														echo $value['p_name'];
					            					}
					            					?>
					            				</td>
					            				<td>
					            					<?php
					            					if( empty($value['p_variant_name']) == false ){
					            					  echo $value['p_variant_name'];
					            					} else {
					            					  echo 'Mặc Định';
					            					}
					            					?>
					            				</td>
												<td>
					            					<?php
					            					if( empty($value['p_variant_price_sales']) == false ){
														echo number_format($value['p_variant_price_sales']);
					            					} elseif(!empty($value['combo_id']) && $value['combo_id'] != 0){
														if(!empty($this->listCombo)){
															$total_price =0;
															foreach($this->listCombo[$value['combo_id']] as $comboDetail){
																$price = $comboDetail['price'];
                                    							$total_price += $price; 
														}
															// echo number_format($total_price);
														echo number_format($value['p_sale']);
															
														}
														// echo number_format($value['price']);
													}else{
														// echo number_format($value['p_price']);
														echo number_format($value['p_sale']);
													}
					            					
					            					?>
					            				</td>
					            				<!-- <td><?php echo number_format($value['price'])?></td> -->
					            				<!-- <td><?php echo number_format($value['p_sale'])?></td> -->
					            				<td><?php echo $value['number']?></td>
					            			</tr>
											<?php 
												if(!empty($value['combo_id']) && $value['combo_id'] != 0){
													if(!empty($this->listCombo)){
														foreach($this->listCombo[$value['combo_id']] as $comboDetail){
														?>
															<tr>
																<td style="border-top:none !important"><?php echo ''?></td>
																<td style="border-top:none !important"><img width="40px" height="40px" src="/upload/images/<?php echo $comboDetail['image']?>" /></td>
																<td style="border-top:none !important"><?php echo $comboDetail['title'] ?></td>
																<td style="border-top:none !important"><?php echo 'Mặc Định';?></td>
																<!-- <td style="border-top:none !important"><?php echo number_format($comboDetail['price'])?></td> -->
																<td style="border-top:none !important"><?php echo number_format($comboDetail['price_sales'])?></td>
																<td style="border-top:none !important"><?php echo $value['number']?></td>
															</tr>
														<?php }		
													}
												} 
											?>
					            			<?php
					            		}
					            	}?>
				                </tbody>
							 </table>
						</div>
					</div>
				</fieldset>
				<input type="hidden" name="id" id="id_order" value="<?php echo $this->info[id]?>">
				<div class="text-right">
					<a href="/admin/order">
						<button type="button"
							class="btn btn-default cancel-btn">
							Hủy bỏ<i class="icon-arrow-right14 position-right"></i>
						</button></a>
					<?php if( (empty($this->info) == false && $this->info['status'] != 5) || (empty($this->info) == true)){ ?>
					<button type="submit" class="btn btn-primary submit-btn">
						Đồng ý <i class="fa fa-plus" aria-hidden="true"></i>
					</button>
					<?php } ?>
				</div>
			</form>
		</div>
	</div>
</div>
<div id="modal_media" class="modal fade" data-keyboard="false"
	data-backdrop="static"></div>