<div class="modal fade" id="modalStatus" tabindex="-1" role="dialog" aria-labelledby="modalstatus" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalstatus">Cập Nhật Status</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      		<div class="col-md-12 ">
				<div class="form-group">
					<label>Trang Thái</label>
					<select class="form-control" id="status-update">
						<?php
						foreach ( Commons::getStatusOrder() as $key => $value ){
							?>
							<option value="<?php echo $key?>" <?php if( $key == @$this->info['status']) { echo 'selected'; }?>><?php echo $value?></option>
							<?php
						}
						?>
					</select>
				</div>
			</div>
			<div class="col-md-12 ">
                            <div class="form-group">
                                <label class="control-label">Ghi Chú Admin</label>
                                <textarea rows="3" placeholder="Ghi Chú Admin" name="reject_reason" id="reject_reason" class="form-control"></textarea>
                            </div>
			</div>
                        <div class="col-md-12 ">
                            <div class="form-group">
                                <label class="control-label col-lg-2">Giảm Giá</label>
                                <input type="number" name="admin_discount" id="admin_discount" placeholder="Giá" class="form-control" data-msg="Vui Lòng Nhập Số Tiền Muốn Giảm" value="<?php echo @$this->info['admin_discount'] ?>">
                            </div>
                        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
        <button type="button" class="btn btn-primary save-status" id="save-status" data-id="" data-user="">Lưu</button>
      </div>
    </div>
  </div>
</div>
<div class="page-header">
	<div class="page-header-content">
		<div class="page-title">
			<h4><i class="icon-cart-add2 position-left"></i> <span class="text-semibold">Đơn Hàng - Danh Sách Đơn Hàng</span></h4>
		</div>
		<div class="heading-elements" style="padding-right: 290px">
			<a onclick="pages.order.deleteAll()" class="btn btn-labeled btn-labeled-right bg-indigo heading-btn">Xóa Tất Cả Order Hủy <b><i class="fa fa-check-circle-o" aria-hidden="true"></i></b></a>
		</div>
		<div class="heading-elements" style="padding-right: 165px">
			<a onclick="pages.order.approveAll()" class="btn btn-labeled btn-labeled-right bg-indigo heading-btn">Duyệt Tất Cả <b><i class="fa fa-check-circle-o" aria-hidden="true"></i></b></a>
		</div>
		<div class="heading-elements">
			<a href="/admin/<?php echo $this->controller?>/detail" class="btn btn-labeled btn-labeled-right bg-blue heading-btn">Tạo Đơn Hàng <b><i class="fa fa-plus" aria-hidden="true"></i></b></a>
		</div>
	</div>
	<div class="breadcrumb-line">
		<ul class="breadcrumb">
			<li><a href="/admin/index/"><i class="icon-home2 position-left"></i> Trang Chủ</a></li>
                        <li><a href="/admin/order">Đơn Hàng</a></li>
			<li class="active">Danh Sách Đơn Hàng</li>
		</ul>
		<!-- tree -->
	</div>
</div>

<div class="content">
	<div class="panel panel-flat">
		<div class="panel-heading">
			<h5 class="panel-title">Danh Sách Đơn Hàng</h5>
		</div>
		<div class="panel-body">
			<form id="searchOrder">
				<div class="col-md-12">
					<div class="col-md-4 ">
						<div class="form-group">
							<label>Đã Thanh Toán</label>
								<select item-type="search" mapping-column="7" class="form-control" placeholder="Trạng Thái" >
									<option value="">Tất Cả</option>
									<option value="0">Chưa Thanh Toán</option>
									<option value="1">Đã Thanh Toán</option>
								</select>
						</div>
					</div>
					<div class="col-md-4 ">
						<div class="form-group">
							<label>Trang Thái</label>
							<select item-type="search" mapping-column="8" class="form-control" placeholder="Trạng Thái" >
								<option value="">Tất Cả</option>
								<?php
								foreach ( Commons::getStatusOrder() as $key => $value ){
									?>
									<option value="<?php echo $key?>" <?php if( $key == @$this->info['status']) { echo 'selected'; }?>><?php echo $value?></option>
									<?php
								}
								?>
							</select>
						</div>
					</div>
					<div class="col-md-4 ">
						<div class="form-group">
							<label><?php echo $this->translate('created-at')?></label>
							<div class="input-group">
								<span class="input-group-addon"><i class="icon-calendar"></i></span>
								<input type="text" item-type="search" mapping-column="9" data-format="yyyy-mm-dd" class="form-control datepicker" placeholder="<?php echo $this->translate('created-at')?>">
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-12">
					<div class="col-md-12">
						<button type="button" class="btn btn-primary seach-form"><i class="fa fa-search" aria-hidden="true"></i>&nbsp;<?php echo $this->translate('search')?></button>
					</div>
				</div>
			</form>
		</div>
		<div style="overflow-x: auto; min-width: 100%;">
			<table id="orderTable" class="table datatable-pagination" style ="width:100%; border-bottom: 1px solid #dddddd;border-top: 1px solid #dddddd;">
				<thead>
					<tr>
						<th width="2%">Mã</th>
						<th width="10%">Sản phẩm</th>
						<th width="10%">Người đặt</th>
						<th width="10%">Số điện thoại</th>
						<th width="10%">Địa chỉ</th>
						<th width="10%">Tỉnh Thành</th>
						<th width="10%">Thành Tiền</th>
						<th width="5%">Thanh Toán</th>
						<th width="10%">Trạng thái</th>
						<th width="5%">Ngày tạo</th>
						<th width="5%">Cập nhật</th>
						<th width="3%"class="text-center">Hành Động</th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>

<style>
	.datatable-header {
		border-bottom: none;
		padding:0px 20px;
	}
	.datatable-footer {
		border-top:none;
		padding: 20px;
	}
	.tooltip-inner {
    max-width: 300px;
    background-color: #333;
    color: #fff;
    padding: 8px 12px;
    font-size: 14px;
    border-radius: 5px;
	}

	.tooltip.bs-tooltip-top .arrow::before {
		border-top-color: #333;
	}

	.tooltip.bs-tooltip-bottom .arrow::before {
		border-bottom-color: #333;
	}

</style>