<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h3><i class="icon-rating3 position-left"></i>Phân Quyền - Danh Sách Quyền</h3>
        </div>
        <div class="heading-elements">
            <a href="/admin/permission/add" class="btn btn-labeled btn-labeled-right bg-blue heading-btn"><?php echo $this->translate('add-permission') ?><b><i class="fa fa-plus" aria-hidden="true"></i></b></a>
        </div>
    </div>
    <div class="breadcrumb-line">
        <ul class="breadcrumb">
            <li><a href="/admin/index/"><i class="icon-home2 position-left"></i> Trang Chủ</a></li>
            <li><a href="/admin/permission/">Phân Quyền</a></li>
            <li class="active">Danh Sách Quyền</li>
        </ul>
    </div>
</div>
<!-- /page header -->
<div class="content">
    <!-- Default ordering -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h4 class="panel-title">Danh Sách Quyền</h4>
        </div>
        <table id="permission_list_dbt" class="table datatable-sorting">
            <thead>
                <tr>
                    <th>#</th>
                    <th><?php echo $this->translate('permission_name') ?></th>
                    <th><?php echo $this->translate('status') ?></th>
                    <th class="text-center"><?php echo $this->translate('action') ?></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <!-- /default ordering -->
</div>
<script type="text/javascript">
    var roleList = '<?php echo json_encode($this->roleList)?>';
</script>